const fs = require('fs');



const mensProductNames = [
  "7 Panel Wool Ball Cap",
  "A Squared T-Shirt Men's",
  "A2B Commuter Pant Men's",
  "A2B Comp Jacket Men's",
  "A2B Comp Vest Men's",
  "A2B Polo Shirt LS Men's",
  "A2B Polo Shirt SS Men's",
  "A2B T-Shirt Men's",
  "A2B Top LS Men's",
  "A2B V-Neck Shirt SS Men's",
  "A2B Vinton Jacket Men's",
  "Abbott Pant Men's",
  "Accelero Comp Zip Neck SS Men's",
  "Accelero Tight Men's",
  "Acrux AR Mountaineering Boot",
  "Acrux SL Leather Approach Shoe Men's",
  "Acrux SL Leather GTX Approach Shoe Men's",
  "Acto FL Jacket Men's",
  "Adahy Hoody Men's",
  "Aerios 10 Backpack",
  "Aerios FL GTX Shoe Men's",
  "Aerios FL Mid GTX Shoe Men's",
  "Alpha AR 20 Backpack",
  "Alpha AR 35 Backpack",
  "Alpha AR Glove",
  "Alpha AR Jacket Men's",
  "Alpha AR Pant Men's",
  "Alpha Comp Pant Men's",
  "Alpha FL 30 Backpack",
  "Alpha FL 45 Backpack",
  "Alpha FL Glove",
  "Alpha FL Jacket Men's",
  "Alpha IS Jacket Men's",
  "Alpha MX Glove",
  "Alpha SK 32 Backpack",
  "Alpha SL Glove",
  "Alpha SV Bib Men's",
  "Alpha SV Jacket Men's",
  "Alpha SV Mitten",
  "Amaran Hoody Men's",
  "Ames Jacket Men's",
  "Anertia Glove Men's",
  "Anzo T-Shirt Men's",
  "Aperture Chalk Bag - Small",
  "Aptin Short Men's",
  "Aptin Zip Hoody Men's",
  "AR-395a Harness Men's",
  "Arakys Approach Shoe Men's",
  "Arc'Word T-Shirt Men's",
  "Archaeopteryx Pullover Hoody Men's",
  "Archaeopteryx T-Shirt LS Men's",
  "Archaeopteryx T-Shirt Men's",
  "Argus Jacket Men's",
  "Arro 22 Backpack",
  "Atlin Chino Pant Men's",
  "Atlin Chino Short Men's",
  "Atom AR Hoody Men's",
  "Atom AR Jacket Men's",
  "Atom LT Hoody Men's",
  "Atom LT Jacket Men's",
  "Atom LT Pant Men's",
  "Atom LT Vest Men's",
  "Atom SL Hoody Men's",
  "Atom SL Vest Men's",
  "Axe Keeper with Dongle",
  "Axino Knicker Men's",
  "Bernal Shirt LS Men's",
  "Beta AR Jacket Men's",
  "Beta AR Pant Men's",
  "Beta LT Jacket Men's",
  "Beta SL Hybrid Jacket Men's",
  "Beta SL Pant Men's",
  "Beta SV Bib Pant Men's",
  "Beta SV Jacket Men's",
  "Bird Cap",
  "Bird Head Toque",
  "Bird Headband",
  "Bird Trucker Hat",
  "Blade 20 Backpack",
  "Blade 28 Backpack",
  "Blade 6 Backpack",
  "Bora AR 50 Backpack Men's",
  "Bora AR 63 Backpack Men's",
  "Bora Mid GTX Hiking Boot Men's",
  "Bora2 Mid GTX Hiking Boot Men's",
  "Brize 25 Backpack",
  "Brize 32 Backpack",
  "Brohm Shirt SS Men's",
  "C40 Chalk Bag",
  "C80 Chalk Bag",
  "Calvus Cap",
  "Calvus Visor",
  "Camosun Parka Men's",
  "Captive Polo Shirt LS Men's",
  "Captive Polo Shirt SS Men's",
  "Cassiar Jacket Men's",
  "Cassiar Pant Men's",
  "Castlegar Toque",
  "Centre T-Shirt Men's",
  "Ceres SV Parka Men's",
  "Cerium LT Hoody Men's",
  "Cerium LT Jacket Men's",
  "Cerium LT Vest Men's",
  "Cerium SL Hoody Men's",
  "Cerium SL Jacket Men's",
  "Cerium SL Vest Men's",
  "Cerium SV Hoody Men's",
  "Chilco Polo Shirt SS Men's",
  "Chilkoot Pant Men's",
  "Chunky Knit Headband",
  "Chunky Knit Toque",
  "Climb Trucker Hat",
  "Conveyor Belt",
  "Cordova Jacket Men's",
  "Cormac Comp Shirt SS Men's",
  "Cormac Crew SS Men's",
  "Cormac Short Men's",
  "Cormac Zip Neck Shirt LS Men's",
  "Covert Cardigan Men's",
  "Covert Case C/O",
  "Covert Hoody Men's",
  "Covert Vest Men's",
  "Crest Toque",
  "Creston Pant Men's",
  "Creston Short 11 Men's",
  "Cronin Pant Men's",
  "Dallen Fleece Hoody Men's",
  "Dallen Fleece Jacket Men's",
  "Dallen Fleece Pullover Men's",
  "Delta LT Hoody Men's",
  "Delta LT Jacket Men's",
  "Delta LT Zip Neck Men's",
  "Diplomat Scarf",
  "Diplomat Toque",
  "Donavan Crew Neck Sweater Men's",
  "Donavan V-Neck Sweater Men's",
  "Down Mitten",
  "Dually Belay Parka Men's",
  "Elaho Cap",
  "Elaho Shirt LS Men's",
  "Elgin Hoody Men's",
  "Emblem T-Shirt Men's",
  "Eris Tank Men's",
  "Ether Crew SS Men's",
  "Firebee AR Parka Men's",
  "Fission Glove",
  "Fission Mitten",
  "Fission SV Jacket Men's",
  "FL-365 Harness Men's",
  "Fortrez Beanie",
  "Fortrez Hoody Men's",
  "Fractus Trucker Hat",
  "Gamma AR Pant Men's",
  "Gamma LT Hoody Men's",
  "Gamma LT Jacket Men's",
  "Gamma LT Pant Men's",
  "Gamma LT Short Men's",
  "Gamma MX Hoody Men's",
  "Gamma MX Jacket Men's",
  "Gamma MX Pant Men's",
  "Glades T-Shirt Men's",
  "Gothic Glove",
  "Granville 10 Courier Bag",
  "Granville 16 Courier Bag",
  "Granville 16 Zip Backpack",
  "Granville 18 Tote",
  "Granville 20 Backpack",
  "Grotto Toque",
  "Gryson Shirt LS Men's",
  "Haku Rope Bag",
  "Hexagonal Trucker Hat",
  "Incendo Hoody Men's",
  "Incendo Pant Men's",
  "Incendo SL Jacket Men's",
  "Incendo Vest Men's",
  "Index 15 Backpack",
  "Index Dopp Kit",
  "Index Large Toiletries Bag",
  "Interstate Jacket Men's",
  "Iser Pant Men's",
  "Kadem Crew Neck LS Men's",
  "Kadem Henley SS Men's",
  "Kappa Hoody Men's",
  "Kaslo Shirt LS Men's",
  "Kaslo Shirt SS Men's",
  "Keppel Trench Coat Men's",
  "Kestros Pant Men's",
  "Knee Caps",
  "Koda Jacket Men's",
  "Konseal FL GTX Shoe Men's",
  "Konseal FL Shoe Men's",
  "Konseal Hoody Men's",
  "Konseal Zip Neck Men's",
  "Kvika Ball Cap",
  "Kyanite Hoody Men's",
  "Kyanite Jacket Men's",
  "Kyanite Vest Men's",
  "Kyson Hoody Men's",
  "Lefroy Pant Men's",
  "Lefroy Short Men's",
  "Lines T-Shirt Men's",
  "Logo Trucker Hat",
  "Macai Jacket Men's",
  "Macro T-Shirt Men's",
  "Magnus Coat Men's",
  "Maka 1 Waistpack",
  "Maka 2 Waistpack",
  "Mantis 26 Backpack",
  "Megalith T-Shirt Men's",
  "Merlon Shirt LS Men's",
  "Mosi Toque",
  "Motus Comp Shirt SS Men's",
  "Motus Crew Neck Shirt LS Men's",
  "Motus Crew Neck Shirt SS Men's",
  "Motus Hat",
  "Mountain Trucker Hat",
  "Nodin Jacket Men's",
  "Norvan 14 Hydration Vest",
  "Norvan 7 Hydration Vest",
  "Norvan Jacket Men's",
  "Norvan LD GTX Shoe Men's",
  "Norvan LD Shoe Men's",
  "Norvan SL GTX Shoe Men's",
  "Norvan SL Hoody Men's",
  "Norvan SL Shoe Men's",
  "Norvan VT GTX Shoe Men's",
  "Norvan VT Shoe Men's",
  "Nu Down Detergent",
  "Nu Technical Detergent",
  "Nuclei AR Jacket Men's",
  "Pack Shelter M",
  "Palisade Pant Men's",
  "Palisade Short Men's",
  "Pelion Comp Shirt SS Men's",
  "Pelion Polo Shirt Men's",
  "Phase AR Balaclava",
  "Phase AR Beanie",
  "Phase AR Bottom Men's",
  "Phase AR Crew LS Men's",
  "Phase AR Headband",
  "Phase AR Neck Gaiter",
  "Phase AR Zip Neck LS Men's",
  "Phase SL Bottom Men's",
  "Phase SL Boxer Short Men's",
  "Phase SL Crew LS Men's",
  "Phase SL Crew SS Men's",
  "Phase SL Zip Neck LS Men's",
  "Phasic Evolution Crew Neck Shirt SS Men's",
  "Phasic Sun Hoody Men's",
  "Playground T-Shirt Men's",
  "Procline AR Boot Men's",
  "Procline AR Carbon Boot Men's",
  "Procline Carbon Boot",
  "Procline Comp Jacket Men's",
  "Product Name",
  "Proton AR Hoody Men's",
  "Proton FL Hoody Men's",
  "Proton LT Hoody Men's",
  "Proton LT Jacket Men's",
  "Proton LT Vest Men's",
  "Quadrants T-Shirt Men's",
  "Rho AR Balaclava",
  "Rho AR Bottom Men's",
  "Rho AR Zip Neck Men's",
  "Rho Glove",
  "Rho LT Boot Cut Bottom Men's",
  "Rho LT Bottom Men's",
  "Rho LT Hooded Zip Neck Men's",
  "Rho LT Zip Neck Men's",
  "Rho LTW Beanie",
  "Rho LTW Neck Gaiter",
  "Rico Jacket Men's",
  "Rico Shacket Men's",
  "Riel Shirt LS Men's",
  "Riel Shirt SS Men's",
  "Rise Toque",
  "Rivet Glove",
  "Rolling Stripe Toque Men's",
  "Rush FL Pant Men's",
  "Rush Jacket Men's",
  "Rush LT Jacket Men's",
  "Rush LT Pant Men's",
  "Rush SV Glove Men's",
  "Russet Pant Men's",
  "Russet Short 12 Men's",
  "Sabre Glove Men's",
  "Sabre Jacket Men's",
  "Sabre LT Jacket Men's",
  "Sabre Pant Men's",
  "Sabreo Pant Men's",
  "Satoro AR Bottom Men's",
  "Satoro AR Boxer Men's",
  "Satoro AR Crew Neck Shirt LS Men's",
  "Satoro AR Zip Neck Shirt LS Men's",
  "Satoro SV Zip Neck LS Men's",
  "Sawyer Coat Men's",
  "Sidewinder Jacket Men's",
  "Sigma FL Pant Men's",
  "Sigma SL Anorak Men's",
  "Sigma SL Pant Men's",
  "Sinsola Hat",
  "Sinsolo Hat",
  "Sirrus Henley LS Men's",
  "Skyline Shirt LS Men's",
  "Skyline Shirt SS Men's",
  "SL-340 Harness",
  "Slingblade 4 Shoulder Bag",
  "Solano Hoody Men's",
  "Solano Jacket Men's",
  "Soleus Short Men's",
  "Squamish Hoody Men's",
  "Starke Pant Men's",
  "Stinger Bib Men's",
  "Stinger Pant Men's",
  "Stowe Pant Men's",
  "Stowe Short Men's",
  "Stradium Jacket Men's",
  "Stradium Pant Men's",
  "Stride Tight Men's",
  "Stryka Hoody Men's",
  "Sullivan Pant Men's",
  "Taped T-Shirt Men's",
  "Tauri Jacket Men's",
  "Teneo Glove",
  "Tenquille Hoody Men's",
  "Therme Parka Men's",
  "Thorium AR Hoody Men's",
  "Thorium AR Jacket Men's",
  "Thorsen Parka Men's",
  "Tirse Trucker Hat",
  "Trino Beanie",
  "Trino Jacket Men's",
  "Trino Tight Men's",
  "V110 Rolling Duffle",
  "V80 Rolling Duffle",
  "Velox Crew SS Men's",
  "Venta Glove",
  "Vestigio Beanie",
  "Voltair 20 Backpack",
  "Voltair 30 Backpack",
  "Voltair LiPo 22.2V Battery",
  "Waffle Toque",
  "Wool Ball Cap",
  "Word Head Long Toque",
  "Word Head Toque",
  "Word On End Full-Zip Hoody Men's",
  "Zeta AR Jacket Men's",
  "Zeta FL Jacket Men's",
  "Zeta LT Jacket Men's",
  "Zeta SL Jacket Men's",
  "Zeta SL Pant Men's"
]


const mensProductUrls = [
  "Mens/Mens Photos/7-Panel-Wool-Ball-Cap-Heather-Grey.jpeg",
  "Mens/Mens Photos/A-Squared-T-Shirt-White.jpeg",
  "Mens/Mens Photos/A2B-Commuter-Pant-Pilot.jpeg",
  "Mens/Mens Photos/A2B-Comp-Jacket-Pilot.jpeg",
  "Mens/Mens Photos/A2B-Comp-Vest-Pilot.jpeg",
  "Mens/Mens Photos/A2B-Polo-Shirt-LS-Hecate-Blue.jpeg",
  "Mens/Mens Photos/A2B-Polo-Shirt-SS-Rohan.jpeg",
  "Mens/Mens Photos/A2B-T-Shirt-Sundara.jpeg",
  "Mens/Mens Photos/A2B-Top-LS-Pegasus-Heather.jpeg",
  "Mens/Mens Photos/A2B-V-Neck-Shirt-SS-Ucluelet.jpeg",
  "Mens/Mens Photos/A2B-Vinton-Jacket-Pilot-Heather.jpeg",
  "Mens/Mens Photos/Abbott-Pant-Tui.jpeg",
  "Mens/Mens Photos/Accelero-Comp-Zip-Neck-SS-Proteus.jpeg",
  "Mens/Mens Photos/Accelero-Tight-Black.jpeg",
  "Mens/Mens Photos/Acrux-AR-Mountaineering-Boot-Black-Cajun.jpeg",
  "Mens/Mens Photos/Acrux-SL-Leather-Approach-Shoe-Neptune-Everglade.jpeg",
  "Mens/Mens Photos/Acrux-SL-Leather-GTX-Approach-Shoe-Wren-Teak.jpeg",
  "Mens/Mens Photos/Acto-FL-Jacket-Stellar.jpeg",
  "Mens/Mens Photos/Adahy-Hoody-Redox.jpeg",
  "Mens/Mens Photos/Aerios-10-Backpack-Raven.jpeg",
  "Mens/Mens Photos/Aerios-FL-GTX-Shoe-Yukon-Orion.jpeg",
  "Mens/Mens Photos/Aerios-FL-Mid-GTX-Shoe-Taan-Forest-Lampyres.jpeg",
  "Mens/Mens Photos/Alpha-AR-20-Backpack-Robotica.jpeg",
  "Mens/Mens Photos/Alpha-AR-35-Backpack-Robotica.jpeg",
  "Mens/Mens Photos/Alpha-AR-Glove-Graphite.jpeg",
  "Mens/Mens Photos/Alpha-AR-Jacket-Pilot.jpeg",
  "Mens/Mens Photos/Alpha-AR-Pant-Pilot.jpeg",
  "Mens/Mens Photos/Alpha-Comp-Pant-Stellar.jpeg",
  "Mens/Mens Photos/Alpha-FL-30-Backpack-Dark-Firoza.jpeg",
  "Mens/Mens Photos/Alpha-FL-45-Backpack-Cardinal.jpeg",
  "Mens/Mens Photos/Alpha-FL-Glove-Graphite-Cardinal.jpeg",
  "Mens/Mens Photos/Alpha-FL-Jacket-Robotica.jpeg",
  "Mens/Mens Photos/Alpha-IS-Jacket-Magma.jpeg",
  "Mens/Mens Photos/Alpha-MX-Glove-Black.jpeg",
  "Mens/Mens Photos/Alpha-SK-32-Backpack-Flare.jpeg",
  "Mens/Mens Photos/Alpha-SK-Strap-50cm-Flare.jpeg",
  "Mens/Mens Photos/Alpha-SK-Strap-65cm-Flare.jpeg",
  "Mens/Mens Photos/Alpha-SL-Glove-Black.jpeg",
  "Mens/Mens Photos/Alpha-SV-Bib-Black.jpeg",
  "Mens/Mens Photos/Alpha-SV-Jacket-Zevan.jpeg",
  "Mens/Mens Photos/Alpha-SV-Mitten-Black.jpeg",
  "Mens/Mens Photos/Amaran-Hoody-Neptune.jpeg",
  "Mens/Mens Photos/Ames-Jacket-Gwaii.jpeg",
  "Mens/Mens Photos/Anertia-Glove-Black.jpeg",
  "Mens/Mens Photos/Anzo-T-Shirt-Sundara.jpeg",
  "Mens/Mens Photos/Aperture-Chalk-Bag---Large-Titanite-Zevan.jpeg",
  "Mens/Mens Photos/Aperture-Chalk-Bag---Small-Titanite-Pegasus.jpeg",
  "Mens/Mens Photos/Aptin-Short-Odyssea.jpeg",
  "Mens/Mens Photos/Aptin-Zip-Hoody-Everglade.jpeg",
  "Mens/Mens Photos/AR-395a-Harness-Pilot-Flare.jpeg",
  "Mens/Mens Photos/Arakys-Approach-Shoe-Redox-Neptune.jpeg",
  "Mens/Mens Photos/Arc-Word-T-Shirt-Lampyre.jpeg",
  "Mens/Mens Photos/Archaeopteryx-Pullover-Hoody-New-Black-Heather.jpeg",
  "Mens/Mens Photos/Archaeopteryx-T-Shirt-LS-Red-Beach.jpeg",
  "Mens/Mens Photos/Archaeopteryx-T-Shirt-Tangent.jpeg",
  "Mens/Mens Photos/Argus-Jacket-Howe-Sound.jpeg",
  "Mens/Mens Photos/Arro-22-Backpack-Silva.jpeg",
  "Mens/Mens Photos/Atlin-Chino-Pant-Robotica.jpeg",
  "Mens/Mens Photos/Atlin-Chino-Short-Robotica.jpeg",
  "Mens/Mens Photos/Atom-AR-Hoody-Tui.jpeg",
  "Mens/Mens Photos/Atom-AR-Jacket-Triton.jpeg",
  "Mens/Mens Photos/Atom-LT-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Atom-LT-Jacket-Tui.jpeg",
  "Mens/Mens Photos/Atom-LT-Pant-Black.jpeg",
  "Mens/Mens Photos/Atom-LT-Vest-Tui.jpeg",
  "Mens/Mens Photos/Atom-SL-Hoody-Tangent.jpeg",
  "Mens/Mens Photos/Atom-SL-Vest-Neptune.jpeg",
  "Mens/Mens Photos/Axe-Keeper-Black.jpeg",
  "Mens/Mens Photos/Axe-Keeper-with-Dongle-Black.jpeg",
  "Mens/Mens Photos/Axino-Knicker-Magnet.jpeg",
  "Mens/Mens Photos/Bernal-Shirt-LS-Fractal.jpeg",
  "Mens/Mens Photos/Beta-AR-Jacket-Ember.jpeg",
  "Mens/Mens Photos/Beta-AR-Pant-Black.jpeg",
  "Mens/Mens Photos/Beta-LT-Jacket-Neptune.jpeg",
  "Mens/Mens Photos/Beta-SL-Hybrid-Jacket-Lampyre.jpeg",
  "Mens/Mens Photos/Beta-SL-Pant-Black.jpeg",
  "Mens/Mens Photos/Beta-SV-Bib-Pant-Triton.jpeg",
  "Mens/Mens Photos/Beta-SV-Jacket-Red-Beach.jpeg",
  "Mens/Mens Photos/Bird-Cap-Taan-Forest.jpeg",
  "Mens/Mens Photos/Bird-Head-Toque-Orion-Olive-Amber.jpeg",
  "Mens/Mens Photos/Bird-Headband-Zaffre-Aurora.jpeg",
  "Mens/Mens Photos/Bird-Trucker-Hat-Levitate-Labyrinth-Delos-Grey.jpeg",
  "Mens/Mens Photos/Blade-6-Backpack-Black.jpeg",
  "Mens/Mens Photos/Blade-20-Backpack-Pilot.jpeg",
  "Mens/Mens Photos/Blade-28-Backpack-Pilot.jpeg",
  "Mens/Mens Photos/Bora-AR-50-Backpack-Borneo-Blue.jpeg",
  "Mens/Mens Photos/Bora-AR-63-Backpack-Titanium.jpeg",
  "Mens/Mens Photos/Bora-Mid-GTX-Hiking-Boot-Tundra-Reed-Green.jpeg",
  "Mens/Mens Photos/Bora2-Mid-GTX-Hiking-Boot-Black-Cajun.jpeg",
  "Mens/Mens Photos/Brize-25-Backpack-Neptune.jpeg",
  "Mens/Mens Photos/Brize-32-Backpack-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Brohm-Shirt-SS-Orions-Belt.jpeg",
  "Mens/Mens Photos/C40-Chalk-Bag-Poseidon.jpeg",
  "Mens/Mens Photos/C80-Chalk-Bag-Poseidon.jpeg",
  "Mens/Mens Photos/Calvus-Cap-White.jpeg",
  "Mens/Mens Photos/Calvus-Visor-White.jpeg",
  "Mens/Mens Photos/Camosun-Parka-Hecate-Blue.jpeg",
  "Mens/Mens Photos/Captive-Polo-Shirt-LS-Pilot.jpeg",
  "Mens/Mens Photos/Captive-Polo-Shirt-SS-Neptune.jpeg",
  "Mens/Mens Photos/Carrier-Duffle-40-Lt-Chandra.jpeg",
  "Mens/Mens Photos/Carrier-Duffle-55-Pilot.jpeg",
  "Mens/Mens Photos/Carrier-Duffle-80-Pilot.jpeg",
  "Mens/Mens Photos/Cassiar-Jacket-Stellar.jpeg",
  "Mens/Mens Photos/Cassiar-Pant-Stellar.jpeg",
  "Mens/Mens Photos/Castlegar-Toque-Stellar-Tui.jpeg",
  "Mens/Mens Photos/Centre-T-Shirt-Tui.jpeg",
  "Mens/Mens Photos/Ceres-SV-Parka-Black.jpeg",
  "Mens/Mens Photos/Cerium-LT-Hoody-Neptune.jpeg",
  "Mens/Mens Photos/Cerium-LT-Jacket-Triton.jpeg",
  "Mens/Mens Photos/Cerium-LT-Vest-Nocturne.jpeg",
  "Mens/Mens Photos/Cerium-SL-Hoody-Tui.jpeg",
  "Mens/Mens Photos/Cerium-SL-Jacket-Redox.jpeg",
  "Mens/Mens Photos/Cerium-SL-Vest-Robotica.jpeg",
  "Mens/Mens Photos/Cerium-SV-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Chilco-Polo-Shirt-SS-Ucluelet.jpeg",
  "Mens/Mens Photos/Chilkoot-Pant-Black.jpeg",
  "Mens/Mens Photos/Chunky-Knit-Headband-Merbau-Heather.jpeg",
  "Mens/Mens Photos/Chunky-Knit-Toque-Nightshadow-Heather.jpeg",
  "Mens/Mens Photos/Climb-Trucker-Hat-Redox-Proteus-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Conveyor-Belt-Proteus.jpeg",
  "Mens/Mens Photos/Cordova-Jacket-Pegasus-Heather.jpeg",
  "Mens/Mens Photos/Cormac-Comp-Shirt-SS-Utopia.jpeg",
  "Mens/Mens Photos/Cormac-Crew-SS-Pilot.jpeg",
  "Mens/Mens Photos/Cormac-Short-Pilot.jpeg",
  "Mens/Mens Photos/Cormac-Zip-Neck-Shirt-LS-Robotica.jpeg",
  "Mens/Mens Photos/Courier-Bag-15-Black.jpeg",
  "Mens/Mens Photos/Covert-Cardigan-Yukon.jpeg",
  "Mens/Mens Photos/Covert-Case-C-O-Pilot.jpeg",
  "Mens/Mens Photos/Covert-Hoody-Pegasus.jpeg",
  "Mens/Mens Photos/Covert-Vest-Pilot.jpeg",
  "Mens/Mens Photos/Crest-Toque-Stellar-Tui.jpeg",
  "Mens/Mens Photos/Creston-Pant-Yukon.jpeg",
  "Mens/Mens Photos/Creston-Short-8-Yukon.jpeg",
  "Mens/Mens Photos/Creston-Short-11-Yukon.jpeg",
  "Mens/Mens Photos/Cronin-Pant-Pilot.jpeg",
  "Mens/Mens Photos/Dallen-Fleece-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Dallen-Fleece-Jacket-Pilot.jpeg",
  "Mens/Mens Photos/Dallen-Fleece-Pullover-Tui.jpeg",
  "Mens/Mens Photos/Delta-LT-Hoody-Yukon.jpeg",
  "Mens/Mens Photos/Delta-LT-Jacket-Yukon.jpeg",
  "Mens/Mens Photos/Delta-LT-Zip-Neck-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Diplomat-Scarf-Nighthawk.jpeg",
  "Mens/Mens Photos/Diplomat-Toque-Nighthawk.jpeg",
  "Mens/Mens Photos/Donavan-Crew-Neck-Sweater-Light-Grey-Heather.jpeg",
  "Mens/Mens Photos/Donavan-V-Neck-Sweater-Elk-Heather.jpeg",
  "Mens/Mens Photos/Down-Mitten-Black.jpeg",
  "Mens/Mens Photos/Dually-Belay-Parka-Black.jpeg",
  "Mens/Mens Photos/Elaho-Cap-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Elaho-Shirt-LS-Nocturne.jpeg",
  "Mens/Mens Photos/Elgin-Hoody-Pilot-Heather.jpeg",
  "Mens/Mens Photos/Emblem-T-Shirt-Red-Beach.jpeg",
  "Mens/Mens Photos/Eris-Tank-Robotica.jpeg",
  "Mens/Mens Photos/Ether-Crew-SS-Iliad.jpeg",
  "Mens/Mens Photos/Firebee-AR-Parka-Triton.jpeg",
  "Mens/Mens Photos/Fission-Glove-Black.jpeg",
  "Mens/Mens Photos/Fission-Mitten-Black.jpeg",
  "Mens/Mens Photos/Fission-SV-Jacket-Triton.jpeg",
  "Mens/Mens Photos/FL-365-Harness-Red-Beach-Flare.jpeg",
  "Mens/Mens Photos/Fortrez-Beanie-Smoke.jpeg",
  "Mens/Mens Photos/Fortrez-Hoody-Zevan.jpeg",
  "Mens/Mens Photos/Fractus-Trucker-Hat-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Gamma-AR-Pant-Nocturne.jpeg",
  "Mens/Mens Photos/Gamma-LT-Hoody-Yukon.jpeg",
  "Mens/Mens Photos/Gamma-LT-Jacket-Robotica.jpeg",
  "Mens/Mens Photos/Gamma-LT-Pant-Tui.jpeg",
  "Mens/Mens Photos/Gamma-LT-Short-Taan-Forest.jpeg",
  "Mens/Mens Photos/Gamma-MX-Hoody-Red-Beach.jpeg",
  "Mens/Mens Photos/Gamma-MX-Jacket-Hecate-Blue.jpeg",
  "Mens/Mens Photos/Gamma-MX-Pant-Gwaii.jpeg",
  "Mens/Mens Photos/Glades-T-Shirt-White.jpeg",
  "Mens/Mens Photos/Gothic-Glove-Radicchio.jpeg",
  "Mens/Mens Photos/Granville-10-Courier-Bag-Pilot.jpeg",
  "Mens/Mens Photos/Granville-16-Courier-Bag-Black.jpeg",
  "Mens/Mens Photos/Granville-16-Zip-Backpack-Pilot.jpeg",
  "Mens/Mens Photos/Granville-18-Tote-Pilot.jpeg",
  "Mens/Mens Photos/Granville-20-Backpack-Pilot.jpeg",
  "Mens/Mens Photos/Grotto-Toque-Zaffre-Baja.jpeg",
  "Mens/Mens Photos/Gryson-Shirt-LS-Pitch.jpeg",
  "Mens/Mens Photos/Haku-Rope-Bag-Pilot-Flare.jpeg",
  "Mens/Mens Photos/Hexagonal-Trucker-Hat-Yukon.jpeg",
  "Mens/Mens Photos/Incendo-Hoody-Robotica.jpeg",
  "Mens/Mens Photos/Incendo-Pant-Odyssea.jpeg",
  "Mens/Mens Photos/Incendo-SL-Jacket-Utopia.jpeg",
  "Mens/Mens Photos/Incendo-Vest-Black.jpeg",
  "Mens/Mens Photos/Index-5---5-Red-Beach.jpeg",
  "Mens/Mens Photos/Index-5-Red-Beach.jpeg",
  "Mens/Mens Photos/Index-10---10-Red-Beach.jpeg",
  "Mens/Mens Photos/Index-10-Red-Beach.jpeg",
  "Mens/Mens Photos/Index-15-Backpack-Robotica.jpeg",
  "Mens/Mens Photos/Index-Dopp-Kit-Red-Beach.jpeg",
  "Mens/Mens Photos/Index-Large-Toiletries-Bag-Red-Beach.jpeg",
  "Mens/Mens Photos/Interstate-Jacket-Proteus.jpeg",
  "Mens/Mens Photos/Iser-Pant-Tui.jpeg",
  "Mens/Mens Photos/Kadem-Crew-Neck-LS-Robotica.jpeg",
  "Mens/Mens Photos/Kadem-Henley-SS-Robotica.jpeg",
  "Mens/Mens Photos/Kappa-Hoody-Proteus.jpeg",
  "Mens/Mens Photos/Kaslo-Shirt-LS-Tui.jpeg",
  "Mens/Mens Photos/Kaslo-Shirt-SS-Sundara.jpeg",
  "Mens/Mens Photos/Keppel-Trench-Coat-Kingfisher.jpeg",
  "Mens/Mens Photos/Kestros-Pant-Yukon.jpeg",
  "Mens/Mens Photos/Knee-Caps-Black.jpeg",
  "Mens/Mens Photos/Koda-Jacket-Kingfisher.jpeg",
  "Mens/Mens Photos/Konseal-FL-GTX-Shoe-Pilot-Safety.jpeg",
  "Mens/Mens Photos/Konseal-FL-Shoe-Shark-Utility.jpeg",
  "Mens/Mens Photos/Konseal-Hoody-Pilot-II.jpeg",
  "Mens/Mens Photos/Konseal-Zip-Neck-Tangent.jpeg",
  "Mens/Mens Photos/Kvika-Ball-Cap-Yukon.jpeg",
  "Mens/Mens Photos/Kyanite-Hoody-Neurostorm.jpeg",
  "Mens/Mens Photos/Kyanite-Jacket-Olive-Amber.jpeg",
  "Mens/Mens Photos/Kyanite-Vest-Hecate-Blue.jpeg",
  "Mens/Mens Photos/Kyson-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Lefroy-Pant-Mongoose.jpeg",
  "Mens/Mens Photos/Lefroy-Short-Mongoose.jpeg",
  "Mens/Mens Photos/Lines-T-Shirt-White.jpeg",
  "Mens/Mens Photos/Logo-Trucker-Hat-Delos-Grey.jpeg",
  "Mens/Mens Photos/Macai-Jacket-Tui.jpeg",
  "Mens/Mens Photos/Macro-T-Shirt-White.jpeg",
  "Mens/Mens Photos/Magnus-Coat-Pilot.jpeg",
  "Mens/Mens Photos/Maka-1-Waistpack-Tui.jpeg",
  "Mens/Mens Photos/Maka-2-Waistpack-Tui.jpeg",
  "Mens/Mens Photos/Mantis-26-Backpack-Silva.jpeg",
  "Mens/Mens Photos/Megalith-T-Shirt-White.jpeg",
  "Mens/Mens Photos/mens.html",
  "Mens/Mens Photos/Merlon-Shirt-LS-Ordos.jpeg",
  "Mens/Mens Photos/Mosi-Toque-Lopi-Heather.jpeg",
  "Mens/Mens Photos/Motus-Comp-Shirt-SS-Utopia.jpeg",
  "Mens/Mens Photos/Motus-Crew-Neck-Shirt-LS-Robotica.jpeg",
  "Mens/Mens Photos/Motus-Crew-Neck-Shirt-SS-Utopia.jpeg",
  "Mens/Mens Photos/Motus-Hat-Black.jpeg",
  "Mens/Mens Photos/Mountain-Trucker-Hat-Proteus-Delos-Grey.jpeg",
  "Mens/Mens Photos/Nodin-Jacket-Robotica.jpeg",
  "Mens/Mens Photos/Norvan-7-Hydration-Vest-Black.jpeg",
  "Mens/Mens Photos/Norvan-14-Hydration-Vest-Black.jpeg",
  "Mens/Mens Photos/Norvan-Jacket-Deep-Cove.jpeg",
  "Mens/Mens Photos/Norvan-LD-GTX-Shoe-Conifer-Everglade.jpeg",
  "Mens/Mens Photos/Norvan-LD-Shoe-Trail-Blaze-Robotica.jpeg",
  "Mens/Mens Photos/Norvan-SL-GTX-Shoe-Lampyres-Neptune.jpeg",
  "Mens/Mens Photos/Norvan-SL-Hoody-Black-Robotica.jpeg",
  "Mens/Mens Photos/Norvan-SL-Shoe-Tangent-Infrared.jpeg",
  "Mens/Mens Photos/Norvan-VT-GTX-Shoe-Orion-LICHEN.jpeg",
  "Mens/Mens Photos/Norvan-VT-Shoe-Deep-Lagoon-Beacon.jpeg",
  "Mens/Mens Photos/Nu-Down-Detergent-No-Color.jpeg",
  "Mens/Mens Photos/Nu-Technical-Detergent-No-Color.jpeg",
  "Mens/Mens Photos/Nuclei-AR-Jacket-Black.jpeg",
  "Mens/Mens Photos/Pack-Shelter-L-Black.jpeg",
  "Mens/Mens Photos/Pack-Shelter-M-Black.jpeg",
  "Mens/Mens Photos/Pack-Shelter-S-Cayenne.jpeg",
  "Mens/Mens Photos/Pack-Shelter-XS-Cayenne.jpeg",
  "Mens/Mens Photos/Palisade-Pant-Mongoose.jpeg",
  "Mens/Mens Photos/Palisade-Short-Neptune.jpeg",
  "Mens/Mens Photos/Pelion-Comp-Shirt-SS-Robotica.jpeg",
  "Mens/Mens Photos/Pelion-Polo-Shirt-Redox.jpeg",
  "Mens/Mens Photos/Phase-AR-Balaclava-Black.jpeg",
  "Mens/Mens Photos/Phase-AR-Beanie-Black.jpeg",
  "Mens/Mens Photos/Phase-AR-Bottom-Black.jpeg",
  "Mens/Mens Photos/Phase-AR-Crew-LS-Stellar.jpeg",
  "Mens/Mens Photos/Phase-AR-Headband-Black.jpeg",
  "Mens/Mens Photos/Phase-AR-Neck-Gaiter-Black.jpeg",
  "Mens/Mens Photos/Phase-AR-Zip-Neck-LS-Stellar.jpeg",
  "Mens/Mens Photos/Phase-SL-Bottom-Black.jpeg",
  "Mens/Mens Photos/Phase-SL-Boxer-Short-Pilot-II.jpeg",
  "Mens/Mens Photos/Phase-SL-Crew-LS-Iliad.jpeg",
  "Mens/Mens Photos/Phase-SL-Crew-SS-Iliad.jpeg",
  "Mens/Mens Photos/Phase-SL-Zip-Neck-LS-Iliad.jpeg",
  "Mens/Mens Photos/Phasic-Evolution-Crew-Neck-Shirt-SS-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Phasic-Sun-Hoody-Robotica.jpeg",
  "Mens/Mens Photos/Playground-T-Shirt-Pilot.jpeg",
  "Mens/Mens Photos/Procline-AR-Boot-Black.jpeg",
  "Mens/Mens Photos/Procline-AR-Carbon-Boot-Black.jpeg",
  "Mens/Mens Photos/Procline-Carbon-Boot-Black-Liken.jpeg",
  "Mens/Mens Photos/Procline-Comp-Jacket-Stellar.jpeg",
  "Mens/Mens Photos/Proton-AR-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Proton-FL-Hoody-Proteus.jpeg",
  "Mens/Mens Photos/Proton-LT-Hoody-Rigel.jpeg",
  "Mens/Mens Photos/Proton-LT-Jacket-Pilot.jpeg",
  "Mens/Mens Photos/Proton-LT-Vest-Pilot.jpeg",
  "Mens/Mens Photos/Quadrants-T-Shirt-White.jpeg",
  "Mens/Mens Photos/Rho-AR-Balaclava-Black.jpeg",
  "Mens/Mens Photos/Rho-AR-Bottom-Black.jpeg",
  "Mens/Mens Photos/Rho-AR-Zip-Neck-Red-Beach.jpeg",
  "Mens/Mens Photos/Rho-Glove-Hecate-Blue.jpeg",
  "Mens/Mens Photos/Rho-LT-Boot-Cut-Bottom-Black.jpeg",
  "Mens/Mens Photos/Rho-LT-Bottom-Black.jpeg",
  "Mens/Mens Photos/Rho-LT-Hooded-Zip-Neck-Neptune.jpeg",
  "Mens/Mens Photos/Rho-LT-Zip-Neck-Stellar.jpeg",
  "Mens/Mens Photos/Rho-LTW-Beanie-Red-Beach.jpeg",
  "Mens/Mens Photos/Rho-LTW-Neck-Gaiter-Triton.jpeg",
  "Mens/Mens Photos/Rico-Jacket-Pegasus.jpeg",
  "Mens/Mens Photos/Rico-Shacket-Pegasus.jpeg",
  "Mens/Mens Photos/Riel-Shirt-LS-Yukon-Gold.jpeg",
  "Mens/Mens Photos/Riel-Shirt-SS-Yukon-Gold.jpeg",
  "Mens/Mens Photos/Rise-Toque-Stellar-Tui.jpeg",
  "Mens/Mens Photos/Rivet-Glove-Black.jpeg",
  "Mens/Mens Photos/Rolling-Stripe-Toque-Whiskey-Jack.jpeg",
  "Mens/Mens Photos/Rush-FL-Pant-Tui.jpeg",
  "Mens/Mens Photos/Rush-Jacket-Serpentine.jpeg",
  "Mens/Mens Photos/Rush-LT-Jacket-Firecracker.jpeg",
  "Mens/Mens Photos/Rush-LT-Pant-Red-Beach.jpeg",
  "Mens/Mens Photos/Rush-SV-Glove-Black.jpeg",
  "Mens/Mens Photos/Russet-Pant-Tui.jpeg",
  "Mens/Mens Photos/Russet-Short-12-Tui.jpeg",
  "Mens/Mens Photos/Sabre-Glove-Black.jpeg",
  "Mens/Mens Photos/Sabre-Jacket-Stellar.jpeg",
  "Mens/Mens Photos/Sabre-LT-Jacket-Serpentine.jpeg",
  "Mens/Mens Photos/Sabre-Pant-Phantom.jpeg",
  "Mens/Mens Photos/Sabreo-Pant-Taan-Forest.jpeg",
  "Mens/Mens Photos/Satoro-AR-Bottom-Black.jpeg",
  "Mens/Mens Photos/Satoro-AR-Boxer-Black.jpeg",
  "Mens/Mens Photos/Satoro-AR-Crew-Neck-Shirt-LS-Light-Hecate.jpeg",
  "Mens/Mens Photos/Satoro-AR-Zip-Neck-Shirt-LS-Black.jpeg",
  "Mens/Mens Photos/Satoro-SV-Zip-Neck-LS-Light-Hecate.jpeg",
  "Mens/Mens Photos/Sawyer-Coat-Pilot.jpeg",
  "Mens/Mens Photos/Sidewinder-Jacket-Tui.jpeg",
  "Mens/Mens Photos/Sigma-FL-Pant-Stellar.jpeg",
  "Mens/Mens Photos/Sigma-SL-Anorak-Proteus.jpeg",
  "Mens/Mens Photos/Sigma-SL-Pant-Taan-Forest.jpeg",
  "Mens/Mens Photos/Sinsola-Hat-Continuum-Robotica.jpeg",
  "Mens/Mens Photos/Sinsolo-Hat-Proteus-Labyrinth.jpeg",
  "Mens/Mens Photos/Sirrus-Henley-LS-Olive-Amber-Heather.jpeg",
  "Mens/Mens Photos/Skyline-Shirt-LS-Odyssea.jpeg",
  "Mens/Mens Photos/Skyline-Shirt-SS-Tui.jpeg",
  "Mens/Mens Photos/SL-340-Harness-Pegasus-Flare.jpeg",
  "Mens/Mens Photos/Slingblade-4-Shoulder-Bag-Tui.jpeg",
  "Mens/Mens Photos/Solano-Hoody-Robotica.jpeg",
  "Mens/Mens Photos/Solano-Jacket-Tui.jpeg",
  "Mens/Mens Photos/Soleus-Short-Odyssea.jpeg",
  "Mens/Mens Photos/Squamish-Hoody-Trail-Blaze.jpeg",
  "Mens/Mens Photos/Starke-Pant-Tui.jpeg",
  "Mens/Mens Photos/Stinger-Bib-Everglade.jpeg",
  "Mens/Mens Photos/Stinger-Pant-Stellar.jpeg",
  "Mens/Mens Photos/Stowe-Pant-Owami.jpeg",
  "Mens/Mens Photos/Stowe-Short-Owami.jpeg",
  "Mens/Mens Photos/Stradium-Jacket-Robotica.jpeg",
  "Mens/Mens Photos/Stradium-Pant-Black.jpeg",
  "Mens/Mens Photos/Stride-Tight-Black.jpeg",
  "Mens/Mens Photos/Stryka-Hoody-Phantom.jpeg",
  "Mens/Mens Photos/Sullivan-Pant-Pilot.jpeg",
  "Mens/Mens Photos/Taped-T-Shirt-White.jpeg",
  "Mens/Mens Photos/Tauri-Jacket-Stellar.jpeg",
  "Mens/Mens Photos/Teneo-Glove-Black.jpeg",
  "Mens/Mens Photos/Tenquille-Hoody-Pilot.jpeg",
  "Mens/Mens Photos/Therme-Parka-Pilot.jpeg",
  "Mens/Mens Photos/Thorium-AR-Hoody-Red-Beach.jpeg",
  "Mens/Mens Photos/Thorium-AR-Jacket-Hecate-Blue.jpeg",
  "Mens/Mens Photos/Thorsen-Parka-Pilot.jpeg",
  "Mens/Mens Photos/Tirse-Trucker-Hat-Robotica.jpeg",
  "Mens/Mens Photos/Trino-Beanie-Black.jpeg",
  "Mens/Mens Photos/Trino-Jacket-Howe-Sound.jpeg",
  "Mens/Mens Photos/Trino-Tight-Black-Black.jpeg",
  "Mens/Mens Photos/V80-Rolling-Duffle-Black.jpeg",
  "Mens/Mens Photos/V110-Rolling-Duffle-Black.jpeg",
];




const mensProductPrices = [
  "35.00",
  "35.00",
  "139.00",
  "275.00",
  "249.00",
  "109.00",
  "99.00",
  "69.00",
  "109.00",
  "69.00",
  "225.00",
  "129.00",
  "75.00",
  "99.00",
  "750.00",
  "180.00",
  "200.00",
  "349.00",
  "149.00",
  "125.00",
  "170.00",
  "185.00",
  "129.00",
  "219.00",
  "189.00",
  "575.00",
  "525.00",
  "325.00",
  "229.00",
  "259.00",
  "159.00",
  "425.00",
  "899.00",
  "89.00",
  "335.00",
  "99.00",
  "625.00",
  "785.00",
  "259.00",
  "199.00",
  "599.00",
  "159.00",
  "69.00",
  "32.00",
  "79.00",
  "139.00",
  "159.00",
  "150.00",
  "35.00",
  "125.00",
  "45.00",
  "35.00",
  "199.00",
  "199.00",
  "99.00",
  "89.00",
  "299.00",
  "279.00",
  "259.00",
  "239.00",
  "249.00",
  "175.00",
  "229.00",
  "149.00",
  "15.00",
  "199.00",
  "109.00",
  "575.00",
  "475.00",
  "525.00",
  "399.00",
  "275.00",
  "549.00",
  "649.00",
  "35.00",
  "35.00",
  "39.00",
  "39.00",
  "189.00",
  "209.00",
  "149.00",
  "499.00",
  "549.00",
  "280.00",
  "330.00",
  "159.00",
  "189.00",
  "89.00",
  "38.00",
  "42.00",
  "35.00",
  "29.00",
  "649.00",
  "79.00",
  "69.00",
  "725.00",
  "575.00",
  "35.00",
  "69.00",
  "849.00",
  "379.00",
  "349.00",
  "249.00",
  "349.00",
  "329.00",
  "225.00",
  "525.00",
  "79.00",
  "525.00",
  "39.00",
  "39.00",
  "39.00",
  "39.00",
  "399.00",
  "75.00",
  "69.00",
  "75.00",
  "95.00",
  "179.00",
  "199.00",
  "199.00",
  "139.00",
  "39.00",
  "129.00",
  "109.00",
  "119.00",
  "149.00",
  "129.00",
  "89.00",
  "149.00",
  "139.00",
  "109.00",
  "69.00",
  "39.00",
  "139.00",
  "129.00",
  "129.00",
  "625.00",
  "39.00",
  "99.00",
  "199.00",
  "35.00",
  "45.00",
  "59.00",
  "949.00",
  "189.00",
  "179.00",
  "689.00",
  "145.00",
  "25.00",
  "199.00",
  "39.00",
  "199.00",
  "249.00",
  "225.00",
  "189.00",
  "139.00",
  "349.00",
  "299.00",
  "299.00",
  "39.00",
  "39.00",
  "169.00",
  "189.00",
  "219.00",
  "109.00",
  "199.00",
  "39.00",
  "119.00",
  "69.00",
  "35.00",
  "139.00",
  "119.00",
  "129.00",
  "89.00",
  "59.00",
  "35.00",
  "55.00",
  "449.00",
  "475.00",
  "95.00",
  "89.00",
  "425.00",
  "99.00",
  "89.00",
  "475.00",
  "119.00",
  "69.00",
  "449.00",
  "185.00",
  "155.00",
  "169.00",
  "139.00",
  "35.00",
  "179.00",
  "159.00",
  "129.00",
  "119.00",
  "109.00",
  "95.00",
  "39.00",
  "39.00",
  "949.00",
  "35.00",
  "549.00",
  "49.00",
  "59.00",
  "149.00",
  "39.00",
  "109.00",
  "39.00",
  "75.00",
  "79.00",
  "69.00",
  "39.00",
  "39.00",
  "199.00",
  "189.00",
  "169.00",
  "349.00",
  "195.00",
  "160.00",
  "185.00",
  "299.00",
  "150.00",
  "200.00",
  "170.00",
  "12.00",
  "12.00",
  "425.00",
  "55.00",
  "159.00",
  "129.00",
  "95.00",
  "115.00",
  "35.00",
  "35.00",
  "79.00",
  "79.00",
  "25.00",
  "25.00",
  "89.00",
  "75.00",
  "45.00",
  "75.00",
  "69.00",
  "85.00",
  "79.00",
  "109.00",
  "35.00",
  "700.00",
  "900.00",
  "1,000.00",
  "475.00",
  "349.00",
  "259.00",
  "299.00",
  "275.00",
  "199.00",
  "35.00",
  "35.00",
  "125.00",
  "145.00",
  "39.00",
  "79.00",
  "89.00",
  "139.00",
  "125.00",
  "35.00",
  "39.00",
  "249.00",
  "275.00",
  "109.00",
  "95.00",
  "39.00",
  "59.00",
  "39.00",
  "325.00",
  "699.00",
  "649.00",
  "499.00",
  "399.00",
  "129.00",
  "99.00",
  "179.00",
  "625.00",
  "649.00",
  "499.00",
  "139.00",
  "109.00",
  "59.00",
  "119.00",
  "139.00",
  "159.00",
  "425.00",
  "749.00",
  "189.00",
  "179.00",
  "169.00",
  "55.00",
  "55.00",
  "69.00",
  "99.00",
  "89.00",
  "119.00",
  "79.00",
  "229.00",
  "209.00",
  "89.00",
  "159.00",
  "109.00",
  "575.00",
  "499.00",
  "99.00",
  "89.00",
  "149.00",
  "99.00",
  "119.00",
  "119.00",
  "109.00",
  "35.00",
  "699.00",
  "119.00",
  "175.00",
  "699.00",
  "325.00",
  "299.00",
  "849.00",
  "35.00",
  "29.00",
  "225.00",
  "149.00",
  "449.00",
  "425.00",
  "65.00",
  "69.00",
  "39.00",
  "1,250.00",
  "1,300.00",
  "320.00",
  "39.00",
  "35.00",
  "39.00",
  "39.00",
  "139.00",
  "475.00",
  "325.00",
  "425.00",
  "299.00",
  "225.00"
];


const ratings = [
  88.1,
  60,
  81.4,
  80,
  70,
  90,
  82.6,
  80,
  100,
  98.1,
  57.84,
  90,
  100,
  92,
  87.,
  84.,
  75.2,
  95,
  92.4,
  86.,
  90,
  91.4,
  80,
  80,
  92.6,
  86.,
  98.1,
  85,
  80,
  87.6,
  60,
  89.,
  91.,
  93.,
  83.6,
  84.,
  88.1,
  94.,
  93.,
  97.2,
  92.8,
  78.2,
  87.6,
  76,
  93.,
  98.1,
  84.,
  79.4,
  80.,
  86.6,
  96.6,
  76,
  89.2,
  80.,
  83.,
  100,
  92,
  90.,
  93.,
  90.,
  92,
  95,
  93.6,
  100,
  100,
  74.2,
  86.,
  86,
  90.,
  84.,
  72.2,
  92.8,
  100,
  94.,
  68,
  90.,
  0,
  100,
  75,
  82,
  85,
  97.2,
  73.4,
  75.2,
  78.,
  84.,
  90.,
  73.4,
  96.6,
  88.6,
  95.,
  61.8,
  83.6,
  91.,
  94.,
  95.,
  86,
  94.,
  80,
  81.4,
  81.,
  83,
  82.4,
  85.,
  82.8,
  86.6,
  76.4,
  86.6,
  88.1,
  0,
  72,
  0,
  89.8,
  82,
  100,
  93.,
  88.1,
  90,
  86.4,
  80,
  87.6,
  80,
  97.2,
  0,
  0,
  95.8,
  66.,
  90,
  96,
  100,
  88.2,
  92.4,
  60,
  96,
  86.6,
  97.2,
  77.,
  96,
  93.,
  91.,
  84.1,
  72.8,
  0,
  88.6,
  86.6,
  77.8,
  65.8,
  94,
  88.2,
  85.8,
  83.,
  100,
  88.1,
  90.,
  86,
  90.,
  84.1,
  90.,
  86.,
  92.6,
  100,
  59.6,
  100,
  100,
  86.6,
  55.1,
  86.6,
  100,
  96.2,
  69,
  80,
  89.,
  86.6,
  83.,
  84.1,
  88.6,
  87.6,
  85,
  80.,
  100,
  0,
  80,
  93.,
  100,
  0,
  76.4,
  100,
  85.,
  81.,
  100,
  91.8,
  89.2,
  86.6,
  0,
  85.2,
  85.2,
  91.4,
  100,
  91.,
  95.8,
  0,
  70.,
  87.6,
  0,
  85,
  100,
  96,
  75.6,
  0,
  93,
  100,
  100,
  96,
  92,
  96.6,
  0,
  92.8,
  89.,
  84.1,
  90,
  61.6,
  84.1,
  80,
  72.2,
  81.,
  80,
  81.,
  100,
  100,
  85,
  86.6,
  82.4,
  86.,
  64,
  88.6,
  80,
  85.8,
  76.6,
  88.4,
  95,
  78.,
  96.6,
  90,
  91.,
  88.1,
  90,
  96.4,
  94.,
  83,
  100,
  40,
  100,
  0,
  94.,
  91.4,
  88.1,
  90.8,
  86.6,
  96.6,
  0,
  88.1,
  97.6,
  98.6,
  76.6,
  90,
  100,
  100,
  98.4,
  91.,
  80.,
  70.,
  75,
  66.,
  0,
  0,
  44.6,
  87.,
  77.2,
  89.8,
  100,
  92,
  88.,
  80,
  100,
  73.4,
  91.,
  88.6,
  84.2,
  93.,
  100,
  83,
  100,
  94.,
  92,
  81.8,
  88.,
  80,
  95,
  93.,
  90,
  90,
  90,
  85.2,
  93.6,
  94.,
  90.,
  68.,
  81.4,
  77,
  94.,
  75.6,
  86,
  80,
  74.8,
  78.,
  100,
  88.6,
  84.1,
  98.2,
  83.,
  0,
  100,
  85.8,
  92,
  82.4,
  83.,
  79.,
  90.,
  80,
  94.,
  93.,
  79.2,
  0,
  80,
  96.6,
  69,
  95,
  0,
  55.1,
  0,
  90.,
  92.4,
  100,
  71.,
  90,
  89.,
  93.,
  94.,
  96,
  85
];


const NumOfRatings = [
  "(5)",
  "(2)",
  "(42)",
  "(1)",
  "(2)",
  "(2)",
  "(8)",
  "(14)",
  "(1)",
  "(10)",
  "(9)",
  "(4)",
  "(4)",
  "(5)",
  "(14)",
  "(13)",
  "(17)",
  "(4)",
  "(21)",
  "(16)",
  "(6)",
  "(7)",
  "(2)",
  "(10)",
  "(8)",
  "(51)",
  "(10)",
  "(16)",
  "(27)",
  "(26)",
  "(13)",
  "(73)",
  "(12)",
  "(6)",
  "(17)",
  "(13)",
  "(15)",
  "(168)",
  "(6)",
  "(7)",
  "(11)",
  "(11)",
  "(8)",
  "(5)",
  "(9)",
  "(10)",
  "(13)",
  "(29)",
  "(23)",
  "(3)",
  "(6)",
  "(20)",
  "(26)",
  "(38)",
  "(12)",
  "(10)",
  "(91)",
  "(38)",
  "(330)",
  "(116)",
  "(25)",
  "(61)",
  "(72)",
  "(10)",
  "(1)",
  "(21)",
  "(13)",
  "(174)",
  "(51)",
  "(66)",
  "(38)",
  "(14)",
  "(1)",
  "(34)",
  "(47)",
  "(77)",
  "(0)",
  "(2)",
  "(28)",
  "(10)",
  "(8)",
  "(7)",
  "(21)",
  "(33)",
  "(73)",
  "(17)",
  "(15)",
  "(12)",
  "(6)",
  "(14)",
  "(25)",
  "(11)",
  "(51)",
  "(9)",
  "(38)",
  "(27)",
  "(10)",
  "(14)",
  "(2)",
  "(14)",
  "(146)",
  "(68)",
  "(26)",
  "(11)",
  "(14)",
  "(12)",
  "(34)",
  "(6)",
  "(10)",
  "(0)",
  "(5)",
  "(0)",
  "(120)",
  "(10)",
  "(3)",
  "(15)",
  "(5)",
  "(4)",
  "(68)",
  "(19)",
  "(40)",
  "(2)",
  "(7)",
  "(0)",
  "(0)",
  "(33)",
  "(3)",
  "(4)",
  "(5)",
  "(4)",
  "(78)",
  "(55)",
  "(4)",
  "(5)",
  "(3)",
  "(7)",
  "(8)",
  "(10)",
  "(3)",
  "(16)",
  "(10)",
  "(25)",
  "(0)",
  "(14)",
  "(21)",
  "(9)",
  "(14)",
  "(79)",
  "(17)",
  "(7)",
  "(68)",
  "(2)",
  "(42)",
  "(47)",
  "(37)",
  "(78)",
  "(5)",
  "(101)",
  "(71)",
  "(24)",
  "(1)",
  "(28)",
  "(1)",
  "(3)",
  "(12)",
  "(4)",
  "(3)",
  "(4)",
  "(32)",
  "(11)",
  "(3)",
  "(56)",
  "(3)",
  "(6)",
  "(5)",
  "(46)",
  "(8)",
  "(8)",
  "(24)",
  "(2)",
  "(0)",
  "(1)",
  "(48)",
  "(1)",
  "(0)",
  "(28)",
  "(2)",
  "(18)",
  "(17)",
  "(7)",
  "(22)",
  "(13)",
  "(3)",
  "(0)",
  "(23)",
  "(23)",
  "(7)",
  "(3)",
  "(19)",
  "(14)",
  "(0)",
  "(27)",
  "(39)",
  "(0)",
  "(20)",
  "(8)",
  "(10)",
  "(9)",
  "(0)",
  "(20)",
  "(2)",
  "(1)",
  "(5)",
  "(10)",
  "(12)",
  "(0)",
  "(11)",
  "(15)",
  "(5)",
  "(34)",
  "(12)",
  "(25)",
  "(4)",
  "(44)",
  "(13)",
  "(17)",
  "(13)",
  "(1)",
  "(3)",
  "(24)",
  "(3)",
  "(68)",
  "(26)",
  "(10)",
  "(7)",
  "(8)",
  "(14)",
  "(12)",
  "(12)",
  "(4)",
  "(15)",
  "(35)",
  "(6)",
  "(50)",
  "(5)",
  "(14)",
  "(11)",
  "(7)",
  "(13)",
  "(2)",
  "(1)",
  "(2)",
  "(0)",
  "(17)",
  "(35)",
  "(5)",
  "(24)",
  "(9)",
  "(6)",
  "(0)",
  "(10)",
  "(17)",
  "(28)",
  "(12)",
  "(4)",
  "(2)",
  "(3)",
  "(24)",
  "(38)",
  "(24)",
  "(23)",
  "(16)",
  "(3)",
  "(0)",
  "(0)",
  "(30)",
  "(11)",
  "(7)",
  "(43)",
  "(3)",
  "(5)",
  "(9)",
  "(4)",
  "(2)",
  "(3)",
  "(53)",
  "(7)",
  "(29)",
  "(3)",
  "(7)",
  "(13)",
  "(8)",
  "(17)",
  "(5)",
  "(11)",
  "(16)",
  "(13)",
  "(8)",
  "(3)",
  "(2)",
  "(10)",
  "(4)",
  "(53)",
  "(28)",
  "(7)",
  "(11)",
  "(7)",
  "(15)",
  "(26)",
  "(84)",
  "(9)",
  "(20)",
  "(20)",
  "(39)",
  "(27)",
  "(2)",
  "(14)",
  "(10)",
  "(32)",
  "(6)",
  "(0)",
  "(4)",
  "(14)",
  "(20)",
  "(66)",
  "(48)",
  "(43)",
  "(15)",
  "(1)",
  "(11)",
  "(29)",
  "(23)",
  "(0)",
  "(2)",
  "(12)",
  "(53)",
  "(12)",
  "(0)",
  "(8)",
  "(0)",
  "(11)",
  "(13)",
  "(3)",
  "(7)",
  "(2)",
  "(48)",
  "(9)",
  "(22)",
  "(10)",
  "(4)"
];


const materials = [
  "Breathable ",
  "GORE-TEX ",
  "Synthetic Fibre ",
  "Natural Fibre ",
  "Nylon ",
  "Fleece ",
  "Lightweight ",
  "Coreloft ",
  "Down Fill ",
  "Phasic ",
  "Synthetic Insulation ",
  "Softshell ",
  "Wool Blend ",
  "Insulated ",
  "Composite Construction"
];


const colors = [
  "INDIANRED",
  "LIGHTCORAL",
  "SALMON",
  "DARKSALMON",
  "LIGHTSALMON",
  "CRIMSON",
  "RED",
  "FIREBRICK",
  "DARKRED",
  "PINK",
  "LIGHTPINK",
  "HOTPINK",
  "DEEPPINK",
  "MEDIUMVIOLETRED",
  "PALEVIOLETRED",
  "LIGHTSALMON",
  "CORAL",
  "TOMATO",
  "ORANGERED",
  "DARKORANGE",
  "ORANGE",
  "GOLD",
  "YELLOW",
  "LIGHTYELLOW",
  "LEMONCHIFFON",
  "LIGHTGOLDENRODYELLOW",
  "PAPAYAWHIP",
  "MOCCASIN",
  "PEACHPUFF",
  "PALEGOLDENROD",
  "KHAKI",
  "DARKKHAKI",
  "LAVENDER",
  "THISTLE",
  "PLUM",
  "VIOLET",
  "ORCHID",
  "FUCHSIA",
  "MAGENTA",
  "MEDIUMORCHID",
  "MEDIUMPURPLE",
  "REBECCAPURPLE",
  "BLUEVIOLET",
  "DARKVIOLET",
  "DARKORCHID",
  "DARKMAGENTA",
  "PURPLE",
  "INDIGO",
  "SLATEBLUE",
  "DARKSLATEBLUE",
  "MEDIUMSLATEBLUE",
  "GREENYELLOW",
  "CHARTREUSE",
  "LAWNGREEN",
  "LIME",
  "LIMEGREEN",
  "PALEGREEN",
  "LIGHTGREEN",
  "MEDIUMSPRINGGREEN",
  "SPRINGGREEN",
  "MEDIUMSEAGREEN",
  "SEAGREEN",
  "FORESTGREEN",
  "GREEN",
  "DARKGREEN",
  "YELLOWGREEN",
  "OLIVEDRAB",
  "OLIVE",
  "DARKOLIVEGREEN",
  "MEDIUMAQUAMARINE",
  "DARKSEAGREEN",
  "LIGHTSEAGREEN",
  "DARKCYAN",
  "TEAL",
  "CYAN",
  "LIGHTCYAN",
  "PALETURQUOISE",
  "AQUAMARINE",
  "TURQUOISE",
  "MEDIUMTURQUOISE",
  "DARKTURQUOISE",
  "CADETBLUE",
  "STEELBLUE",
  "LIGHTSTEELBLUE",
  "POWDERBLUE",
  "LIGHTBLUE",
  "SKYBLUE",
  "LIGHTSKYBLUE",
  "DEEPSKYBLUE",
  "DODGERBLUE",
  "CORNFLOWERBLUE",
  "MEDIUMSLATEBLUE",
  "ROYALBLUE",
  "BLUE",
  "MEDIUMBLUE",
  "DARKBLUE",
  "NAVY",
  "MIDNIGHTBLUE",
  "CORNSILK",
  "BLANCHEDALMOND",
  "BISQUE",
  "NAVAJOWHITE",
  "WHEAT",
  "BURLYWOOD",
  "ROSYBROWN",
  "SANDYBROWN",
  "GOLDENROD",
  "DARKGOLDENROD",
  "PERU",
  "CHOCOLATE",
  "SADDLEBROWN",
  "SIENNA",
  "BROWN",
  "MAROON",
  "WHITE",
  "SNOW",
  "HONEYDEW",
  "MINTCREAM",
  "AZURE",
  "ALICEBLUE",
  "GHOSTWHITE",
  "WHITESMOKE",
  "SEASHELL",
  "BEIGE",
  "OLDLACE",
  "FLORALWHITE",
  "IVORY",
  "ANTIQUEWHITE",
  "LINEN",
  "LAVENDERBLUSH",
  "MISTYROSE",
  "GAINSBORO",
  "LIGHTGRAY",
  "SILVER",
  "DARKGRAY",
  "GRAY",
  "DIMGRAY",
  "LIGHTSLATEGRAY",
  "SLATEGRAY",
  "DARKSLATEGRAY",
  "BLACK",
];


const activities = [
  "Around Town ",
  "All Round",
  "Hiking",
  "Trekking",
  "Alpine Climbing",
  "Travel/Commute",
  "Running",
  "Ice Climbing",
  "Rock Climbing",
  "Ski/Snowboard",
  "Training/Fitness",
  "Backcountry Skiing",
  "Ski Alpinism",
  "Big Mountain Skiing",
  "Expedition",
  "Nordic/Snowshoeing",
  "Mixed Climbing",
  "Freeride & Freeride Touring",
];


const adjectives = [

  "Dunsinane",
  "Lochnagar",
  "Slieve Croob",
  "Slieve Donard",
  "Snowdon",
  "Soufrière",
  "Iztaccíhuatl",
  "Denali",
  "Mount Elbert",
  "Mount Fairweather",
  "Mount Frissell",
  "Granite Peak",
  "Guadalupe Peak",
  "Haleakala",
  "High Point",
  "Mount Hood",
  "Hualalai",
  "Humphreys Peak",
  "Mount Katahdin",
  "Kilauea",
  "Kings Peak",
  "Lassen Peak",
  "Mauna Kea",
  "Mauna Loa",
  "Mount Mitchell",
  "Mount Monadnock",
  "Mount Nebo",
  "Mount Rainier",
  "Mount Rogers",
  "Mount Rushmore",
  "Mount Saint Elias",
  "San Francisco Peaks",
  "Sassafras Mountain",
  "Mount Shasta",
  "Mount Aconcagua",
  "Maipo Volcano",
  "Cerro Mercedario",
  "Mount Tupungato",
  "Bandeira Peak",
  "Mount Corcovado",
  "Neblina Peak",
  "Sugar Loaf",
  "Chimborazo",
  "Cotopaxi",
  "Double Crested Cormorant",
  "Great Blue Heron",
  "Great Egret",
  "Mute Swan",
  "Canada Goose",
  "Mallard",
  "Turkey Vulture",
  "Osprey",
  "Bald Eagle",
  "Sharp-Shinned Hawk",
  "Red-Tailed Hawk",
  "American Kestrel",
  "Peregrine Falcon",
  "Wild Turkey",
  "Killdeer",
  "Sanderling",
  "Laughing Gull",
  "Herring Gull",
  "Common Tern",
  "Rock Dove",
  "Mourning Dove",
  "Great Horned Owl",
  "Eastern Screech Owl",
  "Downy Woodpecker",
  "Red-Bellied Woodpecker",
  "Northern Flicker",
  "Tree Swallow",
  "Blue Jay",
  "American Crow",
  "Black-capped Chickadee",
  "Tufted Titmouse",
  "Eastern Bluebird",
  "American Robin",
  "Gray Catbird",
  "Northern Mockingbird",
  "Red-Eyed Vireo",
  "Yellow-rumped Warbler",
  "Northern Mockingbird",
  "Northern Cardinal",
  "White-Throated sparrow",
  "Song Sparrow",
  "Dark-Eyed Junco",
  "Red-Winged Blackbird",
  "Common Grackle",
  "House Finch",
  "American Goldfinch",
  "House Sparrow",
  "European Starling",
  "Apple and Pear",
  "Ash",
  "Aspen and Cottonwood and Poplar",
  "Basswood",
  "Birch",
  "Buckeye",
  "Buckthorn",
  "California-laurel",
  "Catalpa",
  "Cedar",
  "Cherry and Plum",
  "Chestnut",
  "Chinkapin",
  "Cottonwood and Poplar and Aspen",
  "Cypress",
  "Dogwood",
  "Douglas-fir",
  "Elm",
  "Fir",
  "Filbert and Hazel",
  "Giant Sequoia",
  "Hawthorn",
  "Hazel and Filbert",
  "Hemlock",
  "Honeylocust",
  "Holly",
  "Horsechestnut",
  "Incense-cedar",
  "Juniper",
  "Larch",
  "Locust",
  "Madrone",
  "Maple",
  "Mountain-ash",
  "Mountain-mahogany",
  "Oak",
  "Oregon-myrtle",
  "Pear and Apple",
  "Pine",
  "Plum and Cherry",
  "Poplar and Aspen and Cottonwood",
  "Redcedar/Arborvitae",
  "Redwood",
  "Russian-olive",
  "Spruce",
  "Sweetgum",
  "Sycamore",
  "Tanoak",
  "True Cedar",
  "True Fir",
  "Walnut",
  "White-cedar",
  "Willow",
  "Yellow-poplar",
  "Yew",
];





const womensProductNames = [
  "7 Panel Wool Ball Cap",
  "A Squared T-Shirt Women's",
  "A2B Scoop Neck Shirt SS Women's",
  "Acrux AR Mountaineering Boot",
  "Acrux SL Leather GTX Approach Shoe Women's",
  "Adahy Hoody Women's",
  "Aerios 10 Backpack",
  "Aerios FL GTX Shoe Women's",
  "Aerios FL Mid GTX Shoe Women's",
  "Airah Jacket Women's",
  "Alpha AR 20 Backpack",
  "Alpha AR 35 Backpack",
  "Alpha AR Glove",
  "Alpha AR Jacket Women's",
  "Alpha AR Pant Women's",
  "Alpha FL 30 Backpack",
  "Alpha FL 45 Backpack",
  "Alpha FL Glove",
  "Alpha FL Jacket Women's",
  "Alpha IS Jacket Women's",
  "Alpha MX Glove",
  "Alpha SK 32 Backpack",
  "Alpha SK Strap 50cm",
  "Alpha SK Strap 65cm",
  "Alpha SL Glove",
  "Alpha SV Jacket Women's",
  "Alpha SV Mitten",
  "Andessa Jacket Women's",
  "Andra Coat Women's",
  "Aperture Chalk Bag - Large",
  "Aperture Chalk Bag - Small",
  "AR-385a Harness Women's",
  "Arakys Approach Shoe Women's",
  "Arc'Word T-Shirt Women's",
  "Archaeopteryx T-Shirt LS Women's",
  "Archaeopteryx Tank Women's",
  "Ardena Tank Women's",
  "Ardena Top Women's",
  "Arro 22 Backpack",
  "Astryl Pant Women's",
  "Atom AR Hoody Women's",
  "Atom LT Hoody Women's",
  "Atom LT Jacket Women's",
  "Atom LT Vest Women's",
  "Atom SL Hoody Women's",
  "Atom SL Vest Women's",
  "Axe Keeper",
  "Axe Keeper with Dongle",
  "Axina Knicker Women's",
  "Beta AR Jacket Women's",
  "Beta AR Pant Women's",
  "Beta LT Jacket Women's",
  "Beta SL Hybrid Jacket Women's",
  "Beta SL Pant Women's",
  "Beta SV Bib Pant Women's",
  "Beta SV Jacket Women's",
  "Bird Cap",
  "Bird Head Toque",
  "Bird Headband",
  "Bird Trucker Hat",
  "Blade 20 Backpack",
  "Blade 28 Backpack",
  "Blade 6 Backpack",
  "Bora AR 49 Backpack Women's",
  "Bora AR 61 Backpack Women's",
  "Bora Mid GTX Hiking Boot Women's",
  "Brize 25 Backpack",
  "Brize 32 Backpack",
  "C40 Chalk Bag",
  "C80 Chalk Bag",
  "Cala Dress Women's",
  "Calvus Cap",
  "Calvus Visor",
  "Carrier Duffle 40",
  "Carrier Duffle 55",
  "Carrier Duffle 80",
  "Castlegar Toque",
  "Centrale Parka Women's",
  "Cerium LT Hoody Women's",
  "Cerium LT Jacket Women's",
  "Cerium LT Vest Women's",
  "Cerium SL Hoody Women's",
  "Cerium SL Vest Women's",
  "Cerium SV Hoody Women's",
  "Chunky Knit Headband",
  "Chunky Knit Toque",
  "Cita Hoody Women's",
  "Cita Pant Women's",
  "Cita SL Jacket Women's",
  "Cita Vest Women's",
  "Climb Trucker Hat",
  "Codetta Coat Women's",
  "Contenta Dress Women's",
  "Contenta Shift Dress Women's",
  "Contenta Shirt LS Women's",
  "Contenta Sleeveless Top Women's",
  "Conveyor Belt",
  "Courier Bag 15",
  "Covert Cardigan Women's",
  "Covert Case C/O",
  "Covert Hoody Women's",
  "Crest Toque",
  "Creston Capri Women's",
  "Creston Pant Women's",
  "Creston Short 10.5 Women's",
  "Creston Short 4.5 Women's",
  "Darrah Coat Women's",
  "Delaney Legging Women's",
  "Delta LT Hoody Women's",
  "Delta LT Jacket Women's",
  "Delta LT Zip Neck Women's",
  "Devis Pant Women's",
  "Devis Short Women's",
  "Diplomat Scarf",
  "Diplomat Toque",
  "Down Mitten",
  "Durant Coat Women's",
  "Edin Pant Women's",
  "Effervescent V-Neck T-Shirt Women's",
  "Elaho Cap",
  "Embra Coat Women's",
  "Fernie Shirt LS Women's",
  "Fernie Toque Women's",
  "Firebee AR Parka Women's",
  "Fission Glove",
  "Fission Mitten",
  "Fission SV Jacket Women's",
  "FL-355 Harness Women's",
  "Fortrez Beanie",
  "Fortrez Hoody Women's",
  "Fractus Trucker Hat",
  "Gaea Jacket Women's",
  "Gamma AR Pant Women's",
  "Gamma LT Hoody Women's",
  "Gamma LT Pant Women's",
  "Gamma LT Short Women's",
  "Gamma MX Hoody Women's",
  "Gamma MX Pant Women's",
  "Gothic Glove",
  "Granville 10 Courier Bag",
  "Granville 16 Courier Bag",
  "Granville 16 Zip Backpack",
  "Granville 18 Tote",
  "Granville 20 Backpack",
  "Grotto Toque",
  "Haku Rope Bag",
  "Hexagonal Trucker Hat",
  "Index 10",
  "Index 10 + 10",
  "Index 15 Backpack",
  "Index 5",
  "Index 5 + 5",
  "Index Dopp Kit",
  "Index Large Toiletries Bag",
  "Jelena Dress Women's",
  "Joni 3/4 Sleeve Top Women's",
  "Kadem Tank Women's",
  "Kadem Top LS Women's",
  "Kadem Top SS Women's",
  "Kakeela Pant Women's",
  "Knee Caps",
  "Konseal FL GTX Shoe Women's",
  "Konseal FL Shoe Women's",
  "Konseal Hoody Women's",
  "Konseal Jacket Women's",
  "Kvika Ball Cap",
  "Kyanite Hoody Women's",
  "Kyanite Jacket Women's",
  "Kyanite Vest Women's",
  "Laina Cardigan Women's",
  "Laina Sweater Women's",
  "Levita Pant Women's",
  "Logo Trucker Hat",
  "Lyra Short Women's",
  "Lyra Skort Women's",
  "Maeven Hoody Women's",
  "Maka 1 Waistpack",
  "Maka 2 Waistpack",
  "Mantis 26 Backpack",
  "Megalith T-Shirt Women's",
  "Mica Pant Women's",
  "Mini-Bird Sweatshirt Women's",
  "Mosi Toque",
  "Motus Crew Neck Shirt LS Women's",
  "Motus Crew Neck Shirt SS Women's",
  "Motus Hat",
  "Mountain Trucker Hat",
  "Murrin Pant Women's",
  "Narin Hoody Women's",
  "Narin Vest Women's",
  "Nila Trench Coat Women's",
  "Nodin Jacket Women's",
  "Norvan 14 Hydration Vest",
  "Norvan 7 Hydration Vest",
  "Norvan Jacket Women's",
  "Norvan LD GTX Shoe Women's",
  "Norvan LD Shoe Women's",
  "Norvan SL GTX Shoe Women's",
  "Norvan SL Hoody Women's",
  "Norvan SL Shoe Women's",
  "Norvan VT GTX Shoe Women's",
  "Norvan VT Shoe Women's",
  "Nu Down Detergent",
  "Nu Technical Detergent",
  "Nuri Coat Women's",
  "Nyara Boatneck Pullover Women's",
  "Nyara Wrap Women's",
  "Nydra Pant Women's",
  "Oriel Legging Women's",
  "Osanna Coat Women's",
  "Pack Shelter L",
  "Pack Shelter M",
  "Pack Shelter S",
  "Pack Shelter XS",
  "Palisade Pant Women's",
  "Patera Parka Women's",
  "Phase AR Balaclava",
  "Phase AR Beanie",
  "Phase AR Bottom Women's",
  "Phase AR Crew LS Women's",
  "Phase AR Headband",
  "Phase AR Neck Gaiter",
  "Phase AR Zip Neck LS Women's",
  "Phase SL Boxer Women's",
  "Phase SL Bra Women's",
  "Phase SL Brief Women's",
  "Phase SL Crew LS Women's",
  "Phase SL Crew SS Women's",
  "Phase SL Zip Neck LS Women's",
  "Phasic Evolution Crew SS Women's",
  "Phasic Sun Hoody Women's",
  "Playground T-Shirt Women's",
  "Procline AR Boot Women's",
  "Procline AR Carbon Boot Women's",
  "Procline Carbon Boot",
  "Proton FL Hoody Women's",
  "Proton LT Hoody Women's",
  "Quadrants T-Shirt Women's",
  "Ravenna Jacket Women's",
  "Ravenna Pant Women's",
  "Rho AR Balaclava",
  "Rho AR Bottom Women's",
  "Rho AR Zip Neck Women's",
  "Rho Glove",
  "Rho LT Boot Cut Bottom Women's",
  "Rho LT Bottom Women's",
  "Rho LT Hooded Zip Neck Women's",
  "Rho LT Zip Neck Women's",
  "Rho LTW Beanie",
  "Rho LTW Neck Gaiter",
  "Riel Shirt LS Women's",
  "Rise Toque",
  "Rivet Glove",
  "Sabria Pant Women's",
  "Sabria Short Women's",
  "Satoro AR Bottom Women's",
  "Satoro AR Crew Neck Shirt LS Women's",
  "Satoro AR Zip Neck Shirt LS Women's",
  "Sentinel Jacket Women's",
  "Sentinel LT Jacket Women's",
  "Sentinel Pant Women's",
  "Serinda Dress Women's",
  "Serres Pant Women's",
  "Shashka FL Pant Women's",
  "Shashka Jacket Women's",
  "Shashka Pant Women's",
  "Sigma FL Pant Women's",
  "Sigma SL Anorak Women's",
  "Sigma SL Pant Women's",
  "Sinsola Hat",
  "Sinsolo Hat",
  "Sirrus Top LS Women's",
  "SL-340 Harness",
  "Slingblade 4 Shoulder Bag",
  "Solano Coat Women's",
  "Solano Hoody Women's",
  "Soltera Dress Women's",
  "Squamish Hoody Women's",
  "Stride Tight Women's",
  "Sunara Tight Women's",
  "Sylvite Pant Women's",
  "Taema Crew Neck Shirt SS Women's",
  "Taema Hoody Women's",
  "Taema Short Women's",
  "Teneo Glove",
  "Tenquille Hoody Women's",
  "Thorium AR Hoody Women's",
  "Tirse Trucker Hat",
  "Tiya Jacket Women's",
  "Tolu Tank Women's",
  "Tolu Top LS Women's",
  "Tolu Top SS Women's",
  "Trino Beanie",
  "Trino Jacket Women's",
  "Trino Tight Women's",
  "V110 Rolling Duffle",
  "V80 Rolling Duffle",
  "Varana Hoody Women's",
  "Venta Glove",
  "Vertices Hoody Women's",
  "Vestigio Beanie",
  "Voltair 20 Backpack",
  "Voltair 30 Backpack",
  "Voltair Battery Power Supply 100-240V",
  "Voltair LiPo 22.2V Battery",
  "Waffle Toque",
  "Wool Ball Cap",
  "Word Head Long Toque",
  "Word Head Toque",
  "Yerba Coat Women's",
  "Zeta AR Jacket Women's",
  "Zeta FL Jacket Women's",
  "Zeta LT Jacket Women's",
  "Zeta SL Jacket Women's",
  "Zeta SL Pant Women's"
];






const womensProductUrls = [
  "Womens/Womens Photos/7-Panel-Wool-Ball-Cap-Heather-Grey.jpeg",
  "Womens/Womens Photos/A-Squared-T-Shirt-W-White.jpeg",
  "Womens/Womens Photos/A2B-Scoop-Neck-Shirt-SS-W-Origami.jpeg",
  "Womens/Womens Photos/Acrux-AR-Mountaineering-Boot-Black-Cajun.jpeg",
  "Womens/Womens Photos/Acrux-SL-Leather-GTX-Approach-Shoe-W-Castor-Gray-SHADOW.jpeg",
  "Womens/Womens Photos/Adahy-Hoody-W-Larix.jpeg",
  "Womens/Womens Photos/Aerios-10-Backpack-Raven.jpeg",
  "Womens/Womens Photos/Aerios-FL-GTX-Shoe-W-Solstice-Iolite.jpeg",
  "Womens/Womens Photos/Aerios-FL-Mid-GTX-Shoe-W-Redox-Boreal-Burn.jpeg",
  "Womens/Womens Photos/Airah-Jacket-W-Zaffre.jpeg",
  "Womens/Womens Photos/Alpha-AR-20-Backpack-Robotica.jpeg",
  "Womens/Womens Photos/Alpha-AR-35-Backpack-Robotica.jpeg",
  "Womens/Womens Photos/Alpha-AR-Glove-Graphite.jpeg",
  "Womens/Womens Photos/Alpha-AR-Jacket-W-Sonora.jpeg",
  "Womens/Womens Photos/Alpha-AR-Pant-W-Pilot.jpeg",
  "Womens/Womens Photos/Alpha-FL-30-Backpack-Dark-Firoza.jpeg",
  "Womens/Womens Photos/Alpha-FL-45-Backpack-Cardinal.jpeg",
  "Womens/Womens Photos/Alpha-FL-Glove-Graphite-Cardinal.jpeg",
  "Womens/Womens Photos/Alpha-FL-Jacket-W-Iolite.jpeg",
  "Womens/Womens Photos/Alpha-IS-Jacket-W-Magma.jpeg",
  "Womens/Womens Photos/Alpha-MX-Glove-Black.jpeg",
  "Womens/Womens Photos/Alpha-SK-32-Backpack-Flare.jpeg",
  "Womens/Womens Photos/Alpha-SK-Strap-50cm-Flare.jpeg",
  "Womens/Womens Photos/Alpha-SK-Strap-65cm-Flare.jpeg",
  "Womens/Womens Photos/Alpha-SL-Glove-Black.jpeg",
  "Womens/Womens Photos/Alpha-SV-Jacket-W-Titanite.jpeg",
  "Womens/Womens Photos/Alpha-SV-Mitten-Black.jpeg",
  "Womens/Womens Photos/Andessa-Jacket-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Andra-Coat-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Aperture-Chalk-Bag---Large-Titanite-Zevan.jpeg",
  "Womens/Womens Photos/Aperture-Chalk-Bag---Small-Titanite-Pegasus.jpeg",
  "Womens/Womens Photos/AR-385a-Harness-W-Pegasus-Titanite.jpeg",
  "Womens/Womens Photos/Arakys-Approach-Shoe-W-Freezing-Fog-Dewdrop.jpeg",
  "Womens/Womens Photos/Arc-Word-T-Shirt-W-White.jpeg",
  "Womens/Womens Photos/Archaeopteryx-T-Shirt-LS-W-Zaffre.jpeg",
  "Womens/Womens Photos/Archaeopteryx-Tank-W-Firoza.jpeg",
  "Womens/Womens Photos/Ardena-Tank-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Ardena-Top-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Arro-22-Backpack-Silva.jpeg",
  "Womens/Womens Photos/Astryl-Pant-W-Shorepine.jpeg",
  "Womens/Womens Photos/Atom-AR-Hoody-W-Pomegranate.jpeg",
  "Womens/Womens Photos/Atom-LT-Hoody-W-Crimson.jpeg",
  "Womens/Womens Photos/Atom-LT-Jacket-W-Crimson.jpeg",
  "Womens/Womens Photos/Atom-LT-Vest-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Atom-SL-Hoody-W-Redox.jpeg",
  "Womens/Womens Photos/Atom-SL-Vest-W-Redox.jpeg",
  "Womens/Womens Photos/Axe-Keeper-Black.jpeg",
  "Womens/Womens Photos/Axe-Keeper-with-Dongle-Black.jpeg",
  "Womens/Womens Photos/Axina-Knicker-W-Magnet.jpeg",
  "Womens/Womens Photos/Beta-AR-Jacket-W-Zaffre.jpeg",
  "Womens/Womens Photos/Beta-AR-Pant-W-Black.jpeg",
  "Womens/Womens Photos/Beta-LT-Jacket-W-Twilight.jpeg",
  "Womens/Womens Photos/Beta-SL-Hybrid-Jacket-W-Iolite.jpeg",
  "Womens/Womens Photos/Beta-SL-Pant-W-Black.jpeg",
  "Womens/Womens Photos/Beta-SV-Bib-Pant-W-Zaffre.jpeg",
  "Womens/Womens Photos/Beta-SV-Jacket-W-Fiddlehead.jpeg",
  "Womens/Womens Photos/Bird-Cap-Taan-Forest.jpeg",
  "Womens/Womens Photos/Bird-Head-Toque-Orion-Olive-Amber.jpeg",
  "Womens/Womens Photos/Bird-Headband-Zaffre-Aurora.jpeg",
  "Womens/Womens Photos/Bird-Trucker-Hat-Levitate-Labyrinth-Delos-Grey.jpeg",
  "Womens/Womens Photos/Blade-6-Backpack-Black.jpeg",
  "Womens/Womens Photos/Blade-20-Backpack-Pilot.jpeg",
  "Womens/Womens Photos/Blade-28-Backpack-Pilot.jpeg",
  "Womens/Womens Photos/Bora-AR-49-Backpack-W-Castaway.jpeg",
  "Womens/Womens Photos/Bora-AR-61-Backpack-W-Winter-Iris.jpeg",
  "Womens/Womens Photos/Bora-Mid-GTX-Hiking-Boot-W-Raku-Lupine.jpeg",
  "Womens/Womens Photos/Brize-25-Backpack-Neptune.jpeg",
  "Womens/Womens Photos/Brize-32-Backpack-Trail-Blaze.jpeg",
  "Womens/Womens Photos/C40-Chalk-Bag-Poseidon.jpeg",
  "Womens/Womens Photos/C80-Chalk-Bag-Poseidon.jpeg",
  "Womens/Womens Photos/Cala-Dress-W-Kirigami.jpeg",
  "Womens/Womens Photos/Calvus-Cap-White.jpeg",
  "Womens/Womens Photos/Calvus-Visor-White.jpeg",
  "Womens/Womens Photos/Carrier-Duffle-40-Lt-Chandra.jpeg",
  "Womens/Womens Photos/Carrier-Duffle-55-Pilot.jpeg",
  "Womens/Womens Photos/Carrier-Duffle-80-Pilot.jpeg",
  "Womens/Womens Photos/Castlegar-Toque-Stellar-Tui.jpeg",
  "Womens/Womens Photos/Centrale-Parka-W-Kingfisher.jpeg",
  "Womens/Womens Photos/Cerium-LT-Hoody-W-Levitate.jpeg",
  "Womens/Womens Photos/Cerium-LT-Jacket-W-Crimson.jpeg",
  "Womens/Womens Photos/Cerium-LT-Vest-W-Shorepine.jpeg",
  "Womens/Womens Photos/Cerium-SL-Hoody-W-Utopia.jpeg",
  "Womens/Womens Photos/Cerium-SL-Vest-W-Iolite.jpeg",
  "Womens/Womens Photos/Cerium-SV-Hoody-W-Pomegranate.jpeg",
  "Womens/Womens Photos/Chunky-Knit-Headband-Merbau-Heather.jpeg",
  "Womens/Womens Photos/Chunky-Knit-Toque-Nightshadow-Heather.jpeg",
  "Womens/Womens Photos/Cita-Hoody-W-Utopia.jpeg",
  "Womens/Womens Photos/Cita-Pant-W-Odyssea.jpeg",
  "Womens/Womens Photos/Cita-SL-Jacket-W-Holograph.jpeg",
  "Womens/Womens Photos/Cita-Vest-W-Robotica.jpeg",
  "Womens/Womens Photos/Climb-Trucker-Hat-Redox-Proteus-Trail-Blaze.jpeg",
  "Womens/Womens Photos/Codetta-Coat-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Contenta-Dress-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Contenta-Shift-Dress-W-Ginger-Root.jpeg",
  "Womens/Womens Photos/Contenta-Shirt-LS-W-Origami.jpeg",
  "Womens/Womens Photos/Contenta-Sleeveless-Top-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Conveyor-Belt-Proteus.jpeg",
  "Womens/Womens Photos/Courier-Bag-15-Black.jpeg",
  "Womens/Womens Photos/Covert-Cardigan-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Covert-Case-C-O-Pilot.jpeg",
  "Womens/Womens Photos/Covert-Hoody-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Crest-Toque-Stellar-Tui.jpeg",
  "Womens/Womens Photos/Creston-Capri-W-Shorepine.jpeg",
  "Womens/Womens Photos/Creston-Pant-W-Theanine.jpeg",
  "Womens/Womens Photos/Creston-Short-4.5-W-Theanine.jpeg",
  "Womens/Womens Photos/Creston-Short-10.5-W-Iolite.jpeg",
  "Womens/Womens Photos/Darrah-Coat-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Delaney-Legging-W-Black.jpeg",
  "Womens/Womens Photos/Delta-LT-Hoody-W-Iolite.jpeg",
  "Womens/Womens Photos/Delta-LT-Jacket-W-Iolite.jpeg",
  "Womens/Womens Photos/Delta-LT-Zip-Neck-W-Iolite.jpeg",
  "Womens/Womens Photos/Devis-Pant-W-Ginger-Root.jpeg",
  "Womens/Womens Photos/Devis-Short-W-Ginger-Root.jpeg",
  "Womens/Womens Photos/Diplomat-Scarf-Nighthawk.jpeg",
  "Womens/Womens Photos/Diplomat-Toque-Nighthawk.jpeg",
  "Womens/Womens Photos/Down-Mitten-Black.jpeg",
  "Womens/Womens Photos/Durant-Coat-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Edin-Pant-W-Black.jpeg",
  "Womens/Womens Photos/Effervescent-V-Neck-T-Shirt-W-Shorepine.jpeg",
  "Womens/Womens Photos/Elaho-Cap-Trail-Blaze.jpeg",
  "Womens/Womens Photos/Embra-Coat-W-Mica-Heather.jpeg",
  "Womens/Womens Photos/Fernie-Shirt-LS-W-Redox.jpeg",
  "Womens/Womens Photos/Fernie-Toque-W-Zaffre.jpeg",
  "Womens/Womens Photos/Firebee-AR-Parka-W-Twilight.jpeg",
  "Womens/Womens Photos/Fission-Glove-Black.jpeg",
  "Womens/Womens Photos/Fission-Mitten-Black.jpeg",
  "Womens/Womens Photos/Fission-SV-Jacket-W-Pomegranate.jpeg",
  "Womens/Womens Photos/FL-355-Harness-W-Poseidon-Titanite.jpeg",
  "Womens/Womens Photos/Fortrez-Beanie-Smoke.jpeg",
  "Womens/Womens Photos/Fortrez-Hoody-W-Dark-Titanite.jpeg",
  "Womens/Womens Photos/Fractus-Trucker-Hat-Trail-Blaze.jpeg",
  "Womens/Womens Photos/Gaea-Jacket-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Gamma-AR-Pant-W-Pomegranate.jpeg",
  "Womens/Womens Photos/Gamma-LT-Hoody-W-Levitate.jpeg",
  "Womens/Womens Photos/Gamma-LT-Pant-W-Robotica.jpeg",
  "Womens/Womens Photos/Gamma-LT-Short-W-Robotica.jpeg",
  "Womens/Womens Photos/Gamma-MX-Hoody-W-Zaffre.jpeg",
  "Womens/Womens Photos/Gamma-MX-Pant-W-Black.jpeg",
  "Womens/Womens Photos/Gothic-Glove-Radicchio.jpeg",
  "Womens/Womens Photos/Granville-10-Courier-Bag-Pilot.jpeg",
  "Womens/Womens Photos/Granville-16-Courier-Bag-Black.jpeg",
  "Womens/Womens Photos/Granville-16-Zip-Backpack-Pilot.jpeg",
  "Womens/Womens Photos/Granville-18-Tote-Pilot.jpeg",
  "Womens/Womens Photos/Granville-20-Backpack-Pilot.jpeg",
  "Womens/Womens Photos/Grotto-Toque-Zaffre-Baja.jpeg",
  "Womens/Womens Photos/Haku-Rope-Bag-Pilot-Flare.jpeg",
  "Womens/Womens Photos/Hexagonal-Trucker-Hat-Yukon.jpeg",
  "Womens/Womens Photos/Index-5---5-Red-Beach.jpeg",
  "Womens/Womens Photos/Index-5-Red-Beach.jpeg",
  "Womens/Womens Photos/Index-10---10-Red-Beach.jpeg",
  "Womens/Womens Photos/Index-10-Red-Beach.jpeg",
  "Womens/Womens Photos/Index-15-Backpack-Robotica.jpeg",
  "Womens/Womens Photos/Index-Dopp-Kit-Red-Beach.jpeg",
  "Womens/Womens Photos/Index-Large-Toiletries-Bag-Red-Beach.jpeg",
  "Womens/Womens Photos/Jelena-Dress-W-Lynx.jpeg",
  "Womens/Womens Photos/Joni-3-4-Sleeve-Top-W-Fawn-Heather.jpeg",
  "Womens/Womens Photos/Kadem-Tank-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Kadem-Top-LS-W-Pekoe.jpeg",
  "Womens/Womens Photos/Kadem-Top-SS-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Kakeela-Pant-W-Crimson.jpeg",
  "Womens/Womens Photos/Knee-Caps-Black.jpeg",
  "Womens/Womens Photos/Konseal-FL-GTX-Shoe-W-Shorepine--Continuum.jpeg",
  "Womens/Womens Photos/Konseal-FL-Shoe-W-Redox-Binary.jpeg",
  "Womens/Womens Photos/Konseal-Hoody-W-Dawn.jpeg",
  "Womens/Womens Photos/Konseal-Jacket-W-Radicchio.jpeg",
  "Womens/Womens Photos/Kvika-Ball-Cap-Yukon.jpeg",
  "Womens/Womens Photos/Kyanite-Hoody-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Kyanite-Jacket-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Kyanite-Vest-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Laina-Cardigan-W-Topi.jpeg",
  "Womens/Womens Photos/Laina-Sweater-W-Topi.jpeg",
  "Womens/Womens Photos/Levita-Pant-W-Iolite.jpeg",
  "Womens/Womens Photos/Logo-Trucker-Hat-Delos-Grey.jpeg",
  "Womens/Womens Photos/Lyra-Short-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Lyra-Skort-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Maeven-Hoody-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Maka-1-Waistpack-Tui.jpeg",
  "Womens/Womens Photos/Maka-2-Waistpack-Tui.jpeg",
  "Womens/Womens Photos/Mantis-26-Backpack-Silva.jpeg",
  "Womens/Womens Photos/Megalith-T-Shirt-W-Zaffre.jpeg",
  "Womens/Womens Photos/Mica-Pant-W-Wells-Grey.jpeg",
  "Womens/Womens Photos/Mini-Bird-Sweatshirt-W-Rhassoul-Heather.jpeg",
  "Womens/Womens Photos/Mosi-Toque-Lopi-Heather.jpeg",
  "Womens/Womens Photos/Motus-Crew-Neck-Shirt-LS-W-Iliad.jpeg",
  "Womens/Womens Photos/Motus-Crew-Neck-Shirt-SS-W-Utopia.jpeg",
  "Womens/Womens Photos/Motus-Hat-Black.jpeg",
  "Womens/Womens Photos/Mountain-Trucker-Hat-Proteus-Delos-Grey.jpeg",
  "Womens/Womens Photos/Murrin-Pant-W-Pilot.jpeg",
  "Womens/Womens Photos/Narin-Hoody-W-Topi.jpeg",
  "Womens/Womens Photos/Narin-Vest-W-Topi.jpeg",
  "Womens/Womens Photos/Nila-Trench-Coat-W-Kingfisher.jpeg",
  "Womens/Womens Photos/Nodin-Jacket-W-Theanine.jpeg",
  "Womens/Womens Photos/Norvan-7-Hydration-Vest-Black.jpeg",
  "Womens/Womens Photos/Norvan-14-Hydration-Vest-Black.jpeg",
  "Womens/Womens Photos/Norvan-Jacket-W-Black-Sapphire.jpeg",
  "Womens/Womens Photos/Norvan-LD-GTX-Shoe-W-Robotica-Auracle.jpeg",
  "Womens/Womens Photos/Norvan-LD-Shoe-W-Utopia-Electrolyte.jpeg",
  "Womens/Womens Photos/Norvan-SL-GTX-Shoe-W-Black-Sapphire-Continuum.jpeg",
  "Womens/Womens Photos/Norvan-SL-Hoody-W-Black-Robotica.jpeg",
  "Womens/Womens Photos/Norvan-SL-Shoe-W-Electrolyte-Nightshadow.jpeg",
  "Womens/Womens Photos/Norvan-VT-GTX-Shoe-W-Baja-Poseidon.jpeg",
  "Womens/Womens Photos/Norvan-VT-Shoe-W-Twilight-Mauveine.jpeg",
  "Womens/Womens Photos/Nu-Down-Detergent-No-Color.jpeg",
  "Womens/Womens Photos/Nu-Technical-Detergent-No-Color.jpeg",
  "Womens/Womens Photos/Nuri-Coat-W-Topi.jpeg",
  "Womens/Womens Photos/Nyara-Boatneck-Pullover-W-Kirigami-Heather.jpeg",
  "Womens/Womens Photos/Nyara-Wrap-W-Kirigami-Heather.jpeg",
  "Womens/Womens Photos/Nydra-Pant-W-Kirigami.jpeg",
  "Womens/Womens Photos/Oriel-Legging-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Osanna-Coat-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Pack-Shelter-L-Black.jpeg",
  "Womens/Womens Photos/Pack-Shelter-M-Black.jpeg",
  "Womens/Womens Photos/Pack-Shelter-S-Cayenne.jpeg",
  "Womens/Womens Photos/Pack-Shelter-XS-Cayenne.jpeg",
  "Womens/Womens Photos/Palisade-Pant-W-Theanine.jpeg",
  "Womens/Womens Photos/Patera-Parka-W-Topi.jpeg",
  "Womens/Womens Photos/Phase-AR-Balaclava-Black.jpeg",
  "Womens/Womens Photos/Phase-AR-Beanie-Black.jpeg",
  "Womens/Womens Photos/Phase-AR-Bottom-W-Black.jpeg",
  "Womens/Womens Photos/Phase-AR-Crew-LS-W-Iolite.jpeg",
  "Womens/Womens Photos/Phase-AR-Headband-Black.jpeg",
  "Womens/Womens Photos/Phase-AR-Neck-Gaiter-Black.jpeg",
  "Womens/Womens Photos/Phase-AR-Zip-Neck-LS-W-Light-Merbau.jpeg",
  "Womens/Womens Photos/Phase-SL-Boxer-W-Dreamscape.jpeg",
  "Womens/Womens Photos/Phase-SL-Bra-W-Dreamscape.jpeg",
  "Womens/Womens Photos/Phase-SL-Brief-W-Dreamscape.jpeg",
  "Womens/Womens Photos/Phase-SL-Crew-LS-W-Illucinate.jpeg",
  "Womens/Womens Photos/Phase-SL-Crew-SS-W-Illucinate.jpeg",
  "Womens/Womens Photos/Phase-SL-Zip-Neck-LS-W-Black.jpeg",
  "Womens/Womens Photos/Phasic-Evolution-Crew-SS-W-Redox.jpeg",
  "Womens/Womens Photos/Phasic-Sun-Hoody-W-Osmosis.jpeg",
  "Womens/Womens Photos/Playground-T-Shirt-W-White.jpeg",
  "Womens/Womens Photos/Procline-AR-Boot-W-Black.jpeg",
  "Womens/Womens Photos/Procline-AR-Carbon-Boot-W-Black-Pretikor.jpeg",
  "Womens/Womens Photos/Procline-Carbon-Boot-Black-Liken.jpeg",
  "Womens/Womens Photos/Proton-FL-Hoody-W-Dark-Illucinate.jpeg",
  "Womens/Womens Photos/Proton-LT-Hoody-W-Macaw.jpeg",
  "Womens/Womens Photos/Quadrants-T-Shirt-W-White.jpeg",
  "Womens/Womens Photos/Ravenna-Jacket-W-Zaffre.jpeg",
  "Womens/Womens Photos/Ravenna-Pant-W-Zaffre.jpeg",
  "Womens/Womens Photos/Rho-AR-Balaclava-Black.jpeg",
  "Womens/Womens Photos/Rho-AR-Bottom-W-Shorepine.jpeg",
  "Womens/Womens Photos/Rho-AR-Zip-Neck-W-Shorepine.jpeg",
  "Womens/Womens Photos/Rho-Glove-Hecate-Blue.jpeg",
  "Womens/Womens Photos/Rho-LT-Boot-Cut-Bottom-W-Black.jpeg",
  "Womens/Womens Photos/Rho-LT-Bottom-W-Iolite.jpeg",
  "Womens/Womens Photos/Rho-LT-Hooded-Zip-Neck-W-Merbau.jpeg",
  "Womens/Womens Photos/Rho-LT-Zip-Neck-W-Titanite.jpeg",
  "Womens/Womens Photos/Rho-LTW-Beanie-Red-Beach.jpeg",
  "Womens/Womens Photos/Rho-LTW-Neck-Gaiter-Triton.jpeg",
  "Womens/Womens Photos/Riel-Shirt-LS-W-Kanna-Stream.jpeg",
  "Womens/Womens Photos/Rise-Toque-Stellar-Tui.jpeg",
  "Womens/Womens Photos/Rivet-Glove-Black.jpeg",
  "Womens/Womens Photos/Sabria-Pant-W-Shorepine.jpeg",
  "Womens/Womens Photos/Sabria-Short-W-Shorepine.jpeg",
  "Womens/Womens Photos/Satoro-AR-Bottom-W-Black.jpeg",
  "Womens/Womens Photos/Satoro-AR-Crew-Neck-Shirt-LS-W-Zaffre.jpeg",
  "Womens/Womens Photos/Satoro-AR-Zip-Neck-Shirt-LS-W-Zaffre.jpeg",
  "Womens/Womens Photos/Sentinel-Jacket-W-Shorepine.jpeg",
  "Womens/Womens Photos/Sentinel-LT-Jacket-W-Twisted-Pine.jpeg",
  "Womens/Womens Photos/Sentinel-Pant-W-Titanite.jpeg",
  "Womens/Womens Photos/Serinda-Dress-W-Light-Grey-Heather.jpeg",
  "Womens/Womens Photos/Serres-Pant-W-Whiskey-Jack.jpeg",
  "Womens/Womens Photos/Shashka-FL-Pant-W-Pilot.jpeg",
  "Womens/Womens Photos/Shashka-Jacket-W-Twisted-Pine.jpeg",
  "Womens/Womens Photos/Shashka-Pant-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Sigma-FL-Pant-W-Black-Sapphire.jpeg",
  "Womens/Womens Photos/Sigma-SL-Anorak-W-Iolite.jpeg",
  "Womens/Womens Photos/Sigma-SL-Pant-W-Robotica.jpeg",
  "Womens/Womens Photos/Sinsola-Hat-Continuum-Robotica.jpeg",
  "Womens/Womens Photos/Sinsolo-Hat-Proteus-Labyrinth.jpeg",
  "Womens/Womens Photos/Sirrus-Top-LS-W-Nightshadow-Heather.jpeg",
  "Womens/Womens Photos/SL-340-Harness-Pegasus-Flare.jpeg",
  "Womens/Womens Photos/Slingblade-4-Shoulder-Bag-Tui.jpeg",
  "Womens/Womens Photos/Solano-Coat-W-Cloudburst.jpeg",
  "Womens/Womens Photos/Solano-Hoody-W-Origami.jpeg",
  "Womens/Womens Photos/Soltera-Dress-W-Redox.jpeg",
  "Womens/Womens Photos/Squamish-Hoody-W-Levitate.jpeg",
  "Womens/Womens Photos/Stride-Tight-W-Black.jpeg",
  "Womens/Womens Photos/Sunara-Tight-W-Odyssea.jpeg",
  "Womens/Womens Photos/Sylvite-Pant-W-Masset.jpeg",
  "Womens/Womens Photos/Taema-Crew-Neck-Shirt-SS-W-Hard-Coral.jpeg",
  "Womens/Womens Photos/Taema-Hoody-W-Robotica.jpeg",
  "Womens/Womens Photos/Taema-Short-W-Dark-Firoza.jpeg",
  "Womens/Womens Photos/Teneo-Glove-Black.jpeg",
  "Womens/Womens Photos/Tenquille-Hoody-W-Petrikor.jpeg",
  "Womens/Womens Photos/Thorium-AR-Hoody-W-Zaffre.jpeg",
  "Womens/Womens Photos/Tirse-Trucker-Hat-Robotica.jpeg",
  "Womens/Womens Photos/Tiya-Jacket-W-Rhassoul.jpeg",
  "Womens/Womens Photos/Tolu-Tank-W-Utopia.jpeg",
  "Womens/Womens Photos/Tolu-Top-LS-W-Fjord.jpeg",
  "Womens/Womens Photos/Tolu-Top-SS-W-Fjord.jpeg",
  "Womens/Womens Photos/Trino-Beanie-Black.jpeg",
  "Womens/Womens Photos/Trino-Jacket-W-Titanite.jpeg",
  "Womens/Womens Photos/Trino-Tight-W-Black-Black.jpeg",
  "Womens/Womens Photos/V80-Rolling-Duffle-Black.jpeg",
  "Womens/Womens Photos/V110-Rolling-Duffle-Black.jpeg",
  "Womens/Womens Photos/Varana-Hoody-W-Clematis.jpeg",
  "Womens/Womens Photos/Venta-Glove-Black.jpeg",
  "Womens/Womens Photos/Vertices-Hoody-W-Shorepine.jpeg",
  "Womens/Womens Photos/Vestigio-Beanie-Lunar-Mist.jpeg",
  "Womens/Womens Photos/Voltair-20-Backpack-Cayenne.jpeg",
  "Womens/Womens Photos/Voltair-30-Backpack-Cayenne.jpeg",
  "Womens/Womens Photos/Voltair-Battery-Power-Supply-100-240V-Black.jpeg",
  "Womens/Womens Photos/Waffle-Toque-Nightshadow.jpeg",
  "Womens/Womens Photos/womens.html",
  "Womens/Womens Photos/Wool-Ball-Cap-Light-Grey-Heather.jpeg",
  "Womens/Womens Photos/Word-Head-Long-Toque-Red-Beach-Nighthawk.jpeg",
  "Womens/Womens Photos/Word-Head-Toque-Zaffre-Titanite.jpeg",
  "Womens/Womens Photos/Yerba-Coat-W-Silva.jpeg",
  "Womens/Womens Photos/Zeta-AR-Jacket-W-Nightshadow.jpeg",
  "Womens/Womens Photos/Zeta-FL-Jacket-W-Iolite.jpeg",
  "Womens/Womens Photos/Zeta-LT-Jacket-W-Redox.jpeg",
  "Womens/Womens Photos/Zeta-SL-Jacket-W-Robotica.jpeg",
  "Womens/Womens Photos/Zeta-SL-Pant-W-Nightshadow.jpeg",
];




const womensProductPrices = [
  "35.00",
  "35.00",
  "69.00",
  "750.00",
  "200.00",
  "149.00",
  "125.00",
  "170.00",
  "185.00",
  "599.00",
  "129.00",
  "219.00",
  "189.00",
  "575.00",
  "525.00",
  "229.00",
  "259.00",
  "159.00",
  "425.00",
  "899.00",
  "89.00",
  "335.00",
  "8.95",
  "9.95",
  "99.00",
  "785.00",
  "259.00",
  "899.00",
  "449.00",
  "36.00",
  "32.00",
  "159.00",
  "150.00",
  "35.00",
  "45.00",
  "29.00",
  "39.00",
  "45.00",
  "199.00",
  "475.00",
  "299.00",
  "259.00",
  "239.00",
  "175.00",
  "229.00",
  "149.00",
  "10.00",
  "15.00",
  "199.00",
  "575.00",
  "475.00",
  "525.00",
  "399.00",
  "275.00",
  "549.00",
  "649.00",
  "35.00",
  "35.00",
  "39.00",
  "39.00",
  "189.00",
  "209.00",
  "149.00",
  "499.00",
  "549.00",
  "280.00",
  "159.00",
  "189.00",
  "38.00",
  "42.00",
  "99.00",
  "35.00",
  "29.00",
  "190.00",
  "210.00",
  "230.00",
  "35.00",
  "799.00",
  "379.00",
  "349.00",
  "249.00",
  "349.00",
  "229.00",
  "525.00",
  "39.00",
  "39.00",
  "139.00",
  "119.00",
  "129.00",
  "89.00",
  "39.00",
  "349.00",
  "89.00",
  "79.00",
  "119.00",
  "59.00",
  "39.00",
  "279.00",
  "179.00",
  "199.00",
  "199.00",
  "39.00",
  "119.00",
  "129.00",
  "99.00",
  "89.00",
  "299.00",
  "89.00",
  "149.00",
  "139.00",
  "109.00",
  "99.00",
  "79.00",
  "69.00",
  "39.00",
  "129.00",
  "549.00",
  "89.00",
  "39.00",
  "39.00",
  "399.00",
  "89.00",
  "35.00",
  "949.00",
  "189.00",
  "179.00",
  "649.00",
  "145.00",
  "25.00",
  "199.00",
  "39.00",
  "199.00",
  "199.00",
  "249.00",
  "189.00",
  "139.00",
  "349.00",
  "299.00",
  "39.00",
  "169.00",
  "189.00",
  "219.00",
  "109.00",
  "199.00",
  "39.00",
  "69.00",
  "35.00",
  "49.00",
  "59.00",
  "59.00",
  "29.00",
  "39.00",
  "35.00",
  "55.00",
  "69.00",
  "89.00",
  "55.00",
  "85.00",
  "65.00",
  "525.00",
  "69.00",
  "185.00",
  "155.00",
  "169.00",
  "149.00",
  "35.00",
  "179.00",
  "159.00",
  "129.00",
  "149.00",
  "119.00",
  "119.00",
  "39.00",
  "75.00",
  "69.00",
  "199.00",
  "49.00",
  "59.00",
  "149.00",
  "39.00",
  "109.00",
  "99.00",
  "39.00",
  "79.00",
  "69.00",
  "39.00",
  "39.00",
  "89.00",
  "249.00",
  "225.00",
  "475.00",
  "199.00",
  "189.00",
  "169.00",
  "349.00",
  "195.00",
  "160.00",
  "185.00",
  "299.00",
  "150.00",
  "200.00",
  "170.00",
  "12.00",
  "12.00",
  "399.00",
  "89.00",
  "99.00",
  "99.00",
  "89.00",
  "449.00",
  "60.00",
  "55.00",
  "50.00",
  "45.00",
  "159.00",
  "649.00",
  "35.00",
  "35.00",
  "75.00",
  "75.00",
  "25.00",
  "25.00",
  "89.00",
  "39.00",
  "45.00",
  "39.00",
  "75.00",
  "69.00",
  "85.00",
  "65.00",
  "109.00",
  "35.00",
  "700.00",
  "900.00",
  "1,000.00",
  "259.00",
  "299.00",
  "35.00",
  "725.00",
  "575.00",
  "35.00",
  "125.00",
  "145.00",
  "39.00",
  "79.00",
  "89.00",
  "139.00",
  "125.00",
  "35.00",
  "39.00",
  "109.00",
  "39.00",
  "59.00",
  "119.00",
  "99.00",
  "109.00",
  "119.00",
  "139.00",
  "625.00",
  "649.00",
  "499.00",
  "75.00",
  "119.00",
  "325.00",
  "649.00",
  "499.00",
  "189.00",
  "179.00",
  "169.00",
  "55.00",
  "55.00",
  "59.00",
  "119.00",
  "79.00",
  "279.00",
  "229.00",
  "75.00",
  "159.00",
  "119.00",
  "85.00",
  "109.00",
  "65.00",
  "129.00",
  "69.00",
  "119.00",
  "175.00",
  "325.00",
  "35.00",
  "799.00",
  "49.00",
  "69.00",
  "59.00",
  "29.00",
  "225.00",
  "149.00",
  "449.00",
  "425.00",
  "99.00",
  "69.00",
  "119.00",
  "39.00",
  "1,250.00",
  "1,300.00",
  "60.00",
  "320.00",
  "39.00",
  "35.00",
  "39.00",
  "39.00",
  "299.00",
  "475.00",
  "325.00",
  "425.00",
  "299.00"
];


const ratingsW = [
  88.00000000000001,
  100,
  100,
  87.20000000000002,
  0,
  100,
  86.19999999999999,
  100,
  90,
  83.39999999999999,
  80,
  80,
  92.6,
  85.8,
  80,
  80,
  87.6,
  60,
  60,
  100,
  93.39999999999999,
  83.6,
  0,
  0,
  84.60000000000001,
  83,
  93.39999999999999,
  80,
  90,
  88.6,
  76,
  95,
  91.4,
  100,
  100,
  0,
  0,
  85,
  80.60000000000001,
  93.39999999999999,
  90.99999999999999,
  92.6,
  94,
  92,
  96.8,
  96.6,
  0,
  100,
  93.39999999999999,
  87.6,
  78.8,
  82.2,
  71.39999999999999,
  80,
  80,
  90,
  68,
  90.99999999999999,
  0,
  100,
  75,
  82,
  85,
  100,
  91.4,
  70,
  84.80000000000001,
  90.60000000000001,
  96.6,
  88.6,
  97.6,
  95.19999999999999,
  61.8,
  100,
  100,
  92,
  94.19999999999999,
  80,
  75.6,
  73.4,
  78.4,
  63,
  60,
  93.80000000000001,
  0,
  72,
  84.00000000000001,
  90,
  100,
  66.60000000000001,
  0,
  82.4,
  81,
  93.39999999999999,
  80,
  0,
  89.8,
  0,
  91.8,
  80,
  86.19999999999999,
  97.2,
  90,
  100,
  0,
  0,
  85.60000000000001,
  94,
  86.6,
  85.2,
  96.4,
  88.00000000000001,
  100,
  60,
  96,
  77.60000000000001,
  73.4,
  64,
  0,
  93.39999999999999,
  100,
  96,
  87.6,
  100,
  77.8,
  65.8,
  84.2,
  72.8,
  85.8,
  82.6,
  100,
  100,
  95,
  85.8,
  90.60000000000001,
  0,
  93.39999999999999,
  94,
  59.199999999999996,
  100,
  100,
  86.6,
  55.00000000000001,
  86.6,
  100,
  69,
  80,
  96.6,
  100,
  88.6,
  93.39999999999999,
  90,
  87.6,
  85,
  100,
  0,
  86.6,
  100,
  100,
  82.6,
  85.60000000000001,
  0,
  66.60000000000001,
  100,
  100,
  0,
  83,
  50,
  100,
  100,
  80,
  77.8,
  70.39999999999999,
  83,
  100,
  93.39999999999999,
  100,
  96,
  75.6,
  100,
  100,
  100,
  100,
  100,
  100,
  96.6,
  0,
  87.4,
  37.6,
  87.20000000000002,
  80,
  100,
  89.39999999999999,
  84.00000000000001,
  87.20000000000002,
  100,
  97.8,
  100,
  97.2,
  100,
  94.19999999999999,
  90,
  100,
  100,
  73.4,
  100,
  100,
  86.6,
  82.2,
  80,
  90,
  86.6,
  0,
  88.80000000000001,
  92,
  80.60000000000001,
  80,
  85.8,
  0,
  86.6,
  95,
  78.60000000000001,
  60,
  80,
  70.8,
  73.4,
  100,
  100,
  100,
  0,
  95,
  100,
  0,
  0,
  0,
  60,
  87.6,
  0,
  90,
  77.60000000000001,
  88.00000000000001,
  90,
  97.6,
  76.6,
  100,
  100,
  100,
  91.19999999999999,
  91.60000000000001,
  80.80000000000001,
  0,
  0,
  44.6,
  80.80000000000001,
  100,
  76.6,
  100,
  95,
  92.8,
  98.2,
  80,
  100,
  100,
  0,
  82.2,
  92.4,
  100,
  0,
  86.6,
  90,
  90,
  85,
  94.19999999999999,
  90.99999999999999,
  100,
  100,
  96.4,
  90,
  95,
  98.00000000000001,
  88.00000000000001,
  0,
  70,
  96,
  85.8,
  100,
  96.8,
  80,
  96,
  80,
  100,
  0,
  94.60000000000001,
  86.6,
  95.60000000000001,
  0,
  80,
  0,
  69,
  98.4,
  95,
  0,
  55.00000000000001,
  60,
  0,
  90.99999999999999,
  92.4,
  100,
  71.39999999999999,
  60,
  92.8,
  0,
  65
];

const NumOfRatingsW = [
  "(5)",
  "(1)",
  "(2)",
  "(14)",
  "(0)",
  "(8)",
  "(16)",
  "(2)",
  "(2)",
  "(6)",
  "(2)",
  "(10)",
  "(8)",
  "(7)",
  "(1)",
  "(27)",
  "(26)",
  "(13)",
  "(2)",
  "(5)",
  "(6)",
  "(17)",
  "(0)",
  "(0)",
  "(13)",
  "(13)",
  "(6)",
  "(13)",
  "(4)",
  "(7)",
  "(5)",
  "(12)",
  "(21)",
  "(7)",
  "(1)",
  "(0)",
  "(0)",
  "(4)",
  "(38)",
  "(3)",
  "(29)",
  "(123)",
  "(33)",
  "(15)",
  "(32)",
  "(6)",
  "(0)",
  "(1)",
  "(12)",
  "(56)",
  "(16)",
  "(18)",
  "(14)",
  "(3)",
  "(2)",
  "(20)",
  "(47)",
  "(77)",
  "(0)",
  "(2)",
  "(28)",
  "(10)",
  "(8)",
  "(2)",
  "(7)",
  "(18)",
  "(17)",
  "(15)",
  "(6)",
  "(14)",
  "(25)",
  "(25)",
  "(11)",
  "(4)",
  "(5)",
  "(5)",
  "(14)",
  "(23)",
  "(46)",
  "(12)",
  "(13)",
  "(13)",
  "(8)",
  "(16)",
  "(0)",
  "(5)",
  "(10)",
  "(4)",
  "(3)",
  "(3)",
  "(0)",
  "(41)",
  "(43)",
  "(3)",
  "(1)",
  "(0)",
  "(120)",
  "(0)",
  "(17)",
  "(19)",
  "(13)",
  "(7)",
  "(2)",
  "(2)",
  "(0)",
  "(0)",
  "(25)",
  "(10)",
  "(3)",
  "(27)",
  "(11)",
  "(5)",
  "(1)",
  "(4)",
  "(5)",
  "(8)",
  "(9)",
  "(5)",
  "(0)",
  "(3)",
  "(2)",
  "(5)",
  "(8)",
  "(3)",
  "(9)",
  "(14)",
  "(19)",
  "(11)",
  "(7)",
  "(8)",
  "(2)",
  "(7)",
  "(8)",
  "(7)",
  "(15)",
  "(0)",
  "(12)",
  "(10)",
  "(28)",
  "(1)",
  "(3)",
  "(12)",
  "(4)",
  "(3)",
  "(4)",
  "(11)",
  "(3)",
  "(6)",
  "(6)",
  "(46)",
  "(3)",
  "(4)",
  "(8)",
  "(8)",
  "(2)",
  "(0)",
  "(3)",
  "(1)",
  "(4)",
  "(8)",
  "(18)",
  "(0)",
  "(9)",
  "(5)",
  "(3)",
  "(0)",
  "(20)",
  "(2)",
  "(1)",
  "(7)",
  "(1)",
  "(9)",
  "(27)",
  "(13)",
  "(6)",
  "(3)",
  "(8)",
  "(10)",
  "(9)",
  "(1)",
  "(2)",
  "(6)",
  "(2)",
  "(2)",
  "(3)",
  "(12)",
  "(0)",
  "(19)",
  "(8)",
  "(14)",
  "(9)",
  "(2)",
  "(15)",
  "(5)",
  "(14)",
  "(3)",
  "(9)",
  "(2)",
  "(21)",
  "(3)",
  "(7)",
  "(2)",
  "(1)",
  "(3)",
  "(27)",
  "(2)",
  "(2)",
  "(3)",
  "(19)",
  "(3)",
  "(2)",
  "(3)",
  "(0)",
  "(9)",
  "(20)",
  "(93)",
  "(8)",
  "(14)",
  "(0)",
  "(3)",
  "(4)",
  "(15)",
  "(3)",
  "(5)",
  "(13)",
  "(6)",
  "(2)",
  "(1)",
  "(4)",
  "(0)",
  "(4)",
  "(1)",
  "(0)",
  "(0)",
  "(0)",
  "(2)",
  "(13)",
  "(0)",
  "(16)",
  "(8)",
  "(10)",
  "(18)",
  "(8)",
  "(12)",
  "(4)",
  "(12)",
  "(2)",
  "(16)",
  "(38)",
  "(24)",
  "(0)",
  "(0)",
  "(30)",
  "(26)",
  "(2)",
  "(6)",
  "(5)",
  "(8)",
  "(25)",
  "(11)",
  "(21)",
  "(3)",
  "(2)",
  "(0)",
  "(9)",
  "(13)",
  "(3)",
  "(0)",
  "(3)",
  "(2)",
  "(10)",
  "(4)",
  "(7)",
  "(11)",
  "(2)",
  "(1)",
  "(11)",
  "(24)",
  "(4)",
  "(10)",
  "(5)",
  "(0)",
  "(2)",
  "(5)",
  "(14)",
  "(5)",
  "(25)",
  "(1)",
  "(10)",
  "(1)",
  "(2)",
  "(0)",
  "(11)",
  "(3)",
  "(9)",
  "(0)",
  "(2)",
  "(0)",
  "(53)",
  "(12)",
  "(12)",
  "(0)",
  "(8)",
  "(1)",
  "(0)",
  "(11)",
  "(13)",
  "(3)",
  "(7)",
  "(7)",
  "(14)",
  "(0)",
  "(8)",
  "(6)",
];







const colorGen = () => {
  var prodColors = [];
  var amount = Math.floor(Math.random() * Math.floor(3)) + 1;
  for (var i = 0; i < amount; i++) {
    var newColor = colors[Math.floor(Math.random() * Math.floor(colors.length - 1))];
    if (!prodColors.includes(newColor)) {
      prodColors.push(newColor);
    }
  }
  return prodColors;
}

const materialGen = () => {
  var prodMaterials = [];
  var amount = Math.floor(Math.random() * Math.floor(2)) + 1;
  for (var i = 0; i < amount; i++) {
    var newMaterial = materials[Math.floor(Math.random() * Math.floor(materials.length - 1))];
    if (!prodMaterials.includes(newMaterial)) {
      prodMaterials.push(newMaterial);
    }
  }
  return prodMaterials;
}

const activityGen = () => {
  var prodActivities = [];
  var amount = Math.floor(Math.random() * Math.floor(2)) + 1;
  for (var i = 0; i < amount; i++) {
    var newActivity = activities[Math.floor(Math.random() * Math.floor(activities.length - 1))];
    if (!prodActivities.includes(newActivity)) {
      prodActivities.push(newActivity);
    }
  }
  return prodActivities;
}


const nameCatAndGW = (originalName) => {
  var result = {};
  words = originalName.split(' ');
  if (words[words.length - 1] === "Women's") {
    result.gender = 'W';
    words.pop();
    result.category = words.pop();
    if (result.category === "SS" || result.category === "LS") {
      result.category = result.category + " Shirt";
    }
    var describer = adjectives[Math.floor(Math.random() * Math.floor(adjectives.length - 1))];
    result.name = describer + " " + result.category;
    return result;
  }
}

const nameCatAndG = (originalName) => {
  var result = {};
  words = originalName.split(' ');
  if (words[words.length - 1] === "Men's") {
    result.gender = 'M';
    words.pop();
  } else {
    result.gender = "U"
  }
  result.category = words.pop();
  if (result.category === "SS" || result.category === "LS") {
    result.category = result.category + " Shirt";
  }
  var describer = adjectives[Math.floor(Math.random() * Math.floor(adjectives.length - 1))];
  result.name = describer + " " + result.category;
  return result;
}


let products = [];

for (var i = 0; i < mensProductNames.length; i++) {
  var product = Object.assign({}, nameCatAndG(mensProductNames[i]));
  product.image = mensProductUrls[i];
  product.price = mensProductPrices[i];
  product.rating = Math.floor(ratings[i]);
  product.numRatings = NumOfRatings[i];
  product.colors = colorGen();
  product.activities = activityGen();
  product.materials = materialGen();
  products.push(product);
}



for (var i = 0; i < womensProductNames.length; i++) {
  var product = Object.assign({}, nameCatAndGW(womensProductNames[i]));
  product.image = womensProductUrls[i];
  product.price = womensProductPrices[i];
  product.rating = Math.floor(ratings[i]);
  product.numRatings = NumOfRatings[i];
  product.colors = colorGen();
  product.activities = activityGen();
  product.materials = materialGen();
  products.push(product);
}


var output = JSON.stringify({ products });

fs.writeFile('products.json', output, 'utf8', () => { console.log('saved') });
